### ISSUE TITLE
Order of exceptions thrown from renaming object stores and indexes differs

### ISSUE THREAD

**Issue by beidson** [w3c/IndexedDB#102]
Order of exceptions thrown from renaming object stores and indexes differs

For IDBIndex, the name attribute’s setter runs these steps:
...
4. If transaction is not an upgrade transaction, throw an InvalidStateError.
5. If transaction is not active, throw a TransactionInactiveError.
6. If index or index’s object store has been deleted, throw an InvalidStateError.
7. If index’s name is equal to name, terminate these steps.
8. If an index named name already exists in index’s object store, throw a ConstraintError.
...

For IDBObjectStore, the name attribute's setter runs these steps:
...
4. If store has been deleted, throw an InvalidStateError.
5. If transaction is not an upgrade transaction, throw an InvalidStateError.
6. If transaction is not active, throw a TransactionInactiveError.
7. If store’s name is equal to name, terminate these steps.
8. If an object store named name already exists in store’s database, throw a ConstraintError.
...

The "if the <object> is deleted..." exception is in different places for each of these, but should be in the same place.

I've been told in a number of other issues that one of the goals of IDB 2.0 is to resolve little unspecified issues like this from IDB 1.0. Let's make sure this new feature doesn't get into 2.0 with the wrong ordering.

**Comment by inexorabletash** [comment]
Can you raise this over on #11 ?
