### ISSUE TITLE
primaryKey compared to object store position is by value rather than key

### ISSUE THREAD

**Issue by brettz9** [w3c/IndexedDB#106]
In the bolded parts here:

> 15. If key is equal to this cursor’s position and primaryKey is **less than** or **equal to** this cursor’s object store position and this cursor’s direction is "next" or "nextunique", throw a DataError.
> 16. If key is equal to this cursor’s position and primaryKey is **greater than** or **equal to** this cursor’s object store position and this cursor’s direction is "prev" or "prevunique", throw a DataError.

...these bolded portions link in code to comparisons based on *key* whereas I think you want them to be comparisons based on value.

**Comment by brettz9** [comment]
@inexorabletash : You mentioned at https://github.com/w3c/IndexedDB/pull/105#issuecomment-257379096 that 

> The phrases you bold are the algorithms for comparing keys in general. The inputs are the *primaryKey* argument and the cursor's *object store position* which are both keys.

...yet I see *object store position* defined as "the cursor also has an object store position, which indicates the value of the previously found record in the index".

Although it of course makes sense that `primaryKey` is a key, I was just thrown off by the definition of *object store position* with which it was being compared indicating "the **value** of the previously found record in the index". I guess this just means that it is *pointing to* the value? I'm just not clear on why "value" is mentioned in that definition if it is just a key. Sorry for my haziness.

**Comment by inexorabletash** [comment]
It's definitely obscure. :) An index is itself defined as an abstract key/value store; the _key_ is the index key and the _value_ is the key of the corresponding object store record, i.e. the primary key. That's how it's defined in:

https://w3c.github.io/IndexedDB/#index-construct
