### ISSUE TITLE
Validate exception ordering against implementations

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#11]
The various "If .... throw ...." statements were left in order from previous iterations of the spec which asserted behavior but didn't define it as formal steps.

We need to verify that the steps match the implementations in the case of conflicts, and reorder if necessary. If implementations disagree, file implementation bugs as necessary.

> NOTE: Checkboxes below indicate that at least 2 implementations and the spec are in alignment.

**Comment by inexorabletash** [comment]
IDBDatabase:
* createObjectStore:
 * FF: InvalidStateError > SyntaxError > ConstraintError > InvalidAccessError
 * Cr: InvalidStateError > TransactionInactiveError > ConstraintError > SyntaxError > InvalidAccessError
* deleteObjectStore
 * FF: InvalidStateError > NotFoundError
 * Cr: InvalidStateError > TransactionInactiveError > NotFoundError
* transaction
 * FF: InvalidStateError > InvalidAccessError (empty) > NotFoundError > InvalidAccessError (mode)
 * Cr: InvalidAccessError (empty) > InvalidAccessError (mode) > InvalidStateError > NotFoundError

**Comment by inexorabletash** [comment]
IDBObjectStore:
* add/put:
 * FF: TransactionInactiveError > ReadOnlyError > DataError
 * Cr: InvalidStateError (deleted) > TransactionInactiveError > ReadOnlyError > DataError
* clear
 * FF: TransactionInactiveError > ReadOnlyError
 * Cr: InvalidStateError (deleted) > TransactionInactiveError > ReadOnlyError
* createIndex
 * FF: SyntaxError > InvalidStateError > ConstraintError > InvalidAccessError
 * Cr: InvalidStateError (deleted) > TransactionInactiveError > SyntaxError > ConstraintError > InvalidAccessError
* delete
 * FF: TransactionInactiveError > ReadOnly > DataError
 * Cr: InvalidStateError (deleted) > TransactionInactiveError > ReadOnly > DataError
* deleteIndex
 * FF: InvalidStateError > NotFoundError
 * Cr: InvalidStateError (deleted) > TransactionInactiveError > NotFoundError
* get/getAll/getAllKeys/count/openCursor/openKeyCursor
 * FF: TransactionInactiveError > DataError
 * Cr: InvalidStateError (deleted) > TransactionInactiveError > DataError

**Comment by inexorabletash** [comment]
IDBIndex
------------
* get/getKey/getAll/getAllKeys/count/openCursor/openKeyCursor
 * FF: TransactionInactiveError > DataError
 * Cr: InvalidStateError (deleted) > TransactionInactiveError > DataError

**Comment by inexorabletash** [comment]
IDBCursor
---------------
* advance
 * FF: TransactionInactiveError > InvalidStateError (got) > TypeError
 * Cr: TypeError > InvalidStateError (got) > InvalidStateError (deleted) > TransactionInactiveError
* continue
 * FF: TransactionInactiveError > InvalidStateError (got) > DataError (key) > DataError (order)
 * Cr: DataError (key) > TransactionInactiveError > InvalidStateError (got) > InvalidStateError (deleted) > DataError (order)
* delete
 * FF: TransactionInactiveError > InvalidStateError (got) > InvalidStateError (key cursor) > ReadOnly
 * Cr: TransactionInactiveError > ReadOnly > InvalidStateError (got) > InvalidStateError (key cursor) > InvalidStateError (deleted)
* update
 * FF: TransactionInactiveError > InvalidStateError (got) > InvalidStateError (key cursor) > ReadOnly > DataError (key)
 * Cr: InvalidStateError (got) > InvalidStateError (key cursor) > InvalidStateError (deleted) > TransactionInactiveError > ReadOnly > DataError (key)

**Comment by inexorabletash** [comment]
IDBTransaction
--------------------
* abort
 * FF:InvalidStateError (finished)
 * Cr: InvalidStateError (finished)
* objectStore
 * FF:InvalidStateError (finished) > NotFoundError 
 * Cr: InvalidStateError (finished) > NotFoundError

**Comment by Velmont** [comment]
Great. At one point we should also get some tests on these things to make it simpler to implement and follow. :)

**Comment by inexorabletash** [comment]
@Velmont - Yes please! Writing tests for these is a bit intimidating, since some cases involve upgrades, many involve async behavior (e.g. trying to use a transaction in a non-IDB callback but before the transaction has committed), etc. And, of course, this is all about combinations of the above. Ugh!

I documented the Blink and Gecko behavior via code inspection, since that was easy.

If anyone wants to help with writing testharness.js-based tests for these please let me know and I'll assist as best I can. I'm also happy to tweak the Chrome ordering; the cursor APIs are particularly funky, but until we have tests I don't want to change anything.

**Comment by inexorabletash** [comment]
Updated notes above for FF based on code inspection, following comments by @benturner  #23

**Comment by inexorabletash** [comment]
Need to Chrome behavior following https://chromium.googlesource.com/chromium/src/+/dce205414aa1bde4125c3129fef24a8dc8ad32cc

**Comment by inexorabletash** [comment]
And tests there can be upstreamed to wpt

**Comment by inexorabletash** [comment]
Following a change yesterday in Chrome, FF and Cr match in all cases. \o/ But we still need tests - there are a bunch to upstream from blink (see _WPT:..._ lines above) - mostly for "v2" stuff or where we have changed to align recently.

**Comment by beidson** [comment]
Order of exceptions thrown from renaming object stores and indexes differs

For IDBIndex, the name attribute’s setter runs these steps:
...
4. If transaction is not an upgrade transaction, throw an InvalidStateError.
5. If transaction is not active, throw a TransactionInactiveError.
6. If index or index’s object store has been deleted, throw an InvalidStateError.
7. If index’s name is equal to name, terminate these steps.
8. If an index named name already exists in index’s object store, throw a ConstraintError.
...

For IDBObjectStore, the name attribute's setter runs these steps:
...
4. If store has been deleted, throw an InvalidStateError.
5. If transaction is not an upgrade transaction, throw an InvalidStateError.
6. If transaction is not active, throw a TransactionInactiveError.
7. If store’s name is equal to name, terminate these steps.
8. If an object store named name already exists in store’s database, throw a ConstraintError.
...

The "if the is deleted..." exception is in different places for each of these, but should be in the same place.

I'm implementing these in WebKit now and *really* don't want to follow the spec on this. Could we pick one or the other?

**Comment by inexorabletash** [comment]
@bevis-tseng and @pwnall - what do you think about making the changes @beidson proposes? i.e. swap the order in one of the two methods?

**Comment by pwnall** [comment]
I'm fine with either order.

While building apps, I used to get thrown off by random errors while debugging my code, so I hope we can converge on _some_ ordering. I can change Chrome to adopt any ordering Firefox and Safari would like to use.

**Comment by bevis-tseng** [comment]
FYI.
These were done in identical order in FF for both IDBObjectStore/IDBIndex [1][2]:
4. If transaction is not an upgrade transaction or if the (store|index) was deleted, throw an InvalidStateError.
5. If transaction is not active, throw a TransactionInactiveError.
6. If the name is identical, terminate these steps.
...

[1] http://searchfox.org/mozilla-central/rev/84075be5067b68dc6cb3b89f999645650e68c05b/dom/indexedDB/IDBObjectStore.cpp#2205-2219
[2] http://searchfox.org/mozilla-central/rev/84075be5067b68dc6cb3b89f999645650e68c05b/dom/indexedDB/IDBIndex.cpp#159-172

**Comment by beidson** [comment]
WebKit now matches Gecko's ordering.
I suggest we codify that.

**Comment by beidson** [comment]
For reference:
https://trac.webkit.org/browser/trunk/Source/WebCore/Modules/indexeddb/IDBIndex.cpp#L82
https://trac.webkit.org/browser/trunk/Source/WebCore/Modules/indexeddb/IDBObjectStore.cpp#L98

**Comment by inexorabletash** [comment]
> WebKit now matches Gecko's ordering.
> I suggest we codify that.

Somehow I missed that comment. Yay!

So far as I know WebKit/Gecko/Blink all match and those match the spec. If that's not the case please submit a web-platform-test case!
