### ISSUE TITLE
Problem with test IndexedDB/idbobjectstore-rename-store.html

### ISSUE THREAD

**Issue by beidson** [w3c/IndexedDB#113]
Problem with test IndexedDB/idbobjectstore-rename-store.html

ToT WebKit fails the 'IndexedDB object store rename covers key generator' part of this test.

The reason appears to be the test, not WebKit.

The test is as follows:

```promise_test(testCase => {
    return createDatabase(testCase, (database, transaction) => {
        createBooksStore(testCase, database);
    }).then(database => {
        const transaction = database.transaction('books', 'readwrite');
        const store = transaction.objectStore('books');
        return checkStoreGenerator(
            testCase, store, 345679,
            'The object store key generator should have the expected state ' +
            'before any renaming').then(() => database.close());
    }).then(() => renameBooksStore(testCase)
    ).then(database => {
        const transaction = database.transaction('renamed_books', 'readwrite');
        const store = transaction.objectStore('renamed_books');
        return checkStoreGenerator(
            testCase, store, 345680,
            'Renaming an object store should not change the state of its key ' +
            'generator').then(() => database.close());
    });
}, 'IndexedDB object store rename covers key generator');
```

The problem is the first checkStoreGenerator line.

That returns a promise that resolves when an IDBRequest.onsuccess handler is called, and in response the test calls db.close().

But the readwrite transaction is still in progress at that point, so the db.close() call aborts the transaction.

This reverts the key generator value which then makes the next half of this test case fail.

When I edit the test to make it return a promise that resolves when the IDBTransaction.oncomplete handler is called, things work as expected and we pass.

I believe the test case is wrong, but am also open to somebody pointing out the language in the spec that says WebKit is wrong.

**Comment by beidson** [comment]
Never mind! The moment I woke up I spotted the issue (We're aborting in-progress transactions on database.close() even though the _forced flag_ isn't set)

The test is fine.

**Comment by inexorabletash** [comment]
Thanks for following up! I'm very glad to see the tests are being helpful here.
