### ISSUE TITLE
DOMStringList should have [Exposed=(Window,Worker)]

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#118]
* Firefox implements DOMStringList with `[Exposed=(Window,Worker)]`
* Chrome does not, but probably should.

I don't think we're saving much by not exposing it in workers (i.e. won't make getting rid of it significantly harder)

**Comment by inexorabletash** [comment]
FYI @domenic @annevk

**Comment by domenic** [comment]
Why add it in workers though? What does that gain us?

**Comment by inexorabletash** [comment]
It's already _used_ in workers (via IDB), just not _exposed_.

**Comment by annevk** [comment]
Makes sense. Which specification should define DOMStringList? DOM or HTML? Indexed DB depends on both already. I guess HTML is the other dependency on DOMStringList, so maybe just put it in HTML somewhere?

**Comment by inexorabletash** [comment]
Resolved by https://github.com/whatwg/html/pull/2192
