### ISSUE TITLE
TLS is the new SSL 

### ISSUE THREAD

**Issue by wseltzer** [w3c/IndexedDB#119]
References to SSL should be updated to TLS (or HTTPS). Consider, should use of IndexedDB require Secure Contexts? https://w3c.github.io/webappsec-secure-contexts/

**Comment by inexorabletash** [comment]
Thanks - filed a PR: https://github.com/w3c/IndexedDB/pull/120

Re: requiring Secure Contexts. If we were inventing IndexedDB from scratch then we probably would consider requiring secure contexts (as we did for the [Cache Storage API](https://w3c.github.io/ServiceWorker/#cache-objects)). As it is, it's widely deployed and used in non-secure contexts so it would be a breaking change.

**Comment by wseltzer** [comment]
Thanks for the SSL->TLS change. Regarding Secure Contexts, it might be worth a non-normative note that new uses are encouraged to require secure context.
