### ISSUE TITLE
Add support for async update or another way to prepopulate the databade

### ISSUE THREAD

**Issue by mariusGundersen** [w3c/IndexedDB#126]
AFAICT there is no way to ensure data has been added to the database during the update from one version to the next, since the update event is sync, not async. And this means there is also no way to do schema updates of existing data in the database (ie, get all entries, change them, and put them back again. 

Any chance this could be added?

**Comment by beidson** [comment]
I'm confused about the premise: upgradeneeded events start an upgrade transaction which allows you to asynchronously do whatever you'd like - both to the schema and contents of the DB.

What precisely is synchronous that you wish would be async?

**Comment by inexorabletash** [comment]
Also curious.

One interpretation might be that when you get the upgradeneeded event you must perform the upgrade within that transaction; you can't fetch the initial data with an async request to the server since you hit the usual transaction autocommit problem.

A pattern that works in that case is to abort the upgrade (via `request.transaction.abort()`), fetch the data, and retry the upgrade.

**Comment by beidson** [comment]
> One interpretation might be that when you get the upgradeneeded event you must perform the upgrade within that transaction; you can't fetch the initial data with an async request to the server since you hit the usual transaction autocommit problem.

Ah - I wasn't even considering a remote server, based on the original question.

That said, if that was the intent...

> A pattern that works in that case is to abort the upgrade (via request.transaction.abort()), fetch the data, and retry the upgrade.

Indeed.

**Comment by mariusGundersen** [comment]
Ok, didn't realize that it would wait for the transaction to complete. I should say that I'm using the idb wrapper, which uses promises instead of the events, so I don't have the deepest of knowledge about indexeddb. 

One problem I've had is that if the promise rejects the upgrade still goes through. But maybe the promise rejection handler could abort the transaction?

**Comment by mariusGundersen** [comment]
Forgot the link: https://github.com/jakearchibald/idb

**Comment by inexorabletash** [comment]
Thanks for clarifying. That's really more of a question for @jakearchibald about his wrapper, then. File an issue there?

(Sensible behavior for adapting IDB to work with Promises is an unsolved [problem](https://github.com/inexorabletash/indexeddb-promises), especially in cases like this.)

**Comment by mariusGundersen** [comment]
I will file an issue there, thank you for your help :)
