### ISSUE TITLE
Remove DOMStringList

### ISSUE THREAD

**Issue by Ms2ger** [w3c/IndexedDB#128]
Adding this here when we're trying to remove it from the platform seems pretty backwards.

**Comment by beidson** [comment]
Was there a new usage of DOMStringList added to IDB 2.0?

If so I agree it should be removed.

But Afaik the DOMStringList usage is preexisting from IDB 1.0

**Comment by Ms2ger** [comment]
I don't understand what, if any, conclusion you expect people to infer from your comment.

**Comment by inexorabletash** [comment]
Duplicate of https://github.com/w3c/IndexedDB/issues/28
