### ISSUE TITLE
Negative counts have inconsistent behavior in getAll()/getAllKeys()

### ISSUE THREAD

**Issue by nolanlawson** [w3c/IndexedDB#131]
If you do:

```js
objectStore.getAll(null, -1);
```

Then Chrome 55 will treat the `-1` as equivalent to `Infinity` (AFAICT) whereas Firefox 50 will throw an error:

    TypeError: Value is out of range for unsigned long

This also happens with `getAllKeys()`.

Looking at the spec, it seems undefined what happens when the `count < 0`:

> If count is specified and there are more than count records in range, only the first count will be retrieved.

The Firefox behavior seems most reasonable to me, although it should probably throw some other error since "unsigned long" is leaking an implementation detail.

**Comment by inexorabletash** [comment]
Since the IDL specifies unsigned long, the algorithm never sees negative values. That's handled at the bindings layer.

The WebIDL spec would define how -1 converts to unsigned long. I don't recall off the top of my head, but without [EnforceRange] it shouldn't throw.

**Comment by inexorabletash** [comment]
It does have [EnforceRange], but I'm on my phone and can't check the specs easily at the moment. Anyway, the behavior is defined.

**Comment by inexorabletash** [comment]
Blink is just missing `[EnforceRange]` - it should throw. 

https://bugs.chromium.org/p/chromium/issues/detail?id=679465

**Comment by inexorabletash** [comment]
Also, re:

> it should probably throw some other error since "unsigned long" is leaking an implementation detail.

The `unsigned long` type is an IDL type, so that's spec not implementation. https://heycam.github.io/webidl/#idl-unsigned-long

A C++ implementation would probably use `uint32_t` for that.
