### ISSUE TITLE
Allow sorting within indexes

### ISSUE THREAD

**Issue by jakearchibald** [w3c/IndexedDB#138]
I imagine this has been suggested before, but I couldn't find an issue for it.

Say I have a series of game instances that look like this:

```js
{isActive: Boolean, started: Date, state: {…}}
```

…can I create an multi-field index where each index is sortable? Eg, I want the active games to be returned before the inactive ones. Within those, I want them returned by "stated" descending.

**Comment by inexorabletash** [comment]
Key order can't be changed, so your choices today are more careful querying or modifying the data before it is indexed. "Order by A ascending, B descending" is a pain. Easiest (I think) is an index on A, and a compound key index  [A,B]; do a unique cursor walk over A and for each A found use another cursor with a prefix range in reverse order on the compound index.

**Comment by inexorabletash** [comment]
Wrapping this sort of thing into a query syntax is #45

**Comment by jakearchibald** [comment]
Fair enough! Happy to have this closed as a dupe.

**Comment by inexorabletash** [comment]
**TPAC 2019 Web Apps Indexed DB triage notes:**

We think this is probably best handled by libraries that can construct indexes dynamically and/or store additional indexable data in each record.
