### ISSUE TITLE
Security and Web Worker access for IndexedDB

### ISSUE THREAD

**Issue by aronallen** [w3c/IndexedDB#141]
We are using Web Workers as a way to run 3rd-party code through established protocols, the code is not completely untrusted, but we are trying to constrain the Web Workers as much as possible.
With Web Workers our platform developers can write small applets without ever accessing the real DOM, and without the same performance bottlenecks as iframes.
We are using Content-Security-Policy to limit what Web Workers can load and access.
Unfortunately there is no way to limit access to IndexedDB, while there are good use-cases to share data between the main thread and Workers with IndexedDB, there may be applications where sharing such data could be a security risk, such as ours.

We believe there should be a way to limit IndexedDB access for Web Workers, perhaps through Content-Security-Policy, so they cannot open the same databases.

Since IndexedDB is still not widely adopted we are not relying on it for our application. In the future IndexedDB could be useful if we could manage security for Web Worker scripts.

**Comment by inexorabletash** [comment]
Pinging @mikewest - for guidance on CSP

I could imagine CSP to limit access to storage, and that applying to Workers. Using it to restrict a single storage API (Indexed DB, Cache API, etc) and potentially even scoped down to particular namespaces within a storage API (in IDB, databases; for Cache, a named cache, etc) seems weird to me but wouldn't be a huge implementation or spec burden. I don't know if that aligns with the vision for CSP though.

**Comment by mikewest** [comment]
This seems like something that would be more likely governed via Feature Policy than CSP. @clelland for comment there. :)

**Comment by clelland** [comment]
Agreed, making IndexedDB a policy-controlled feature would restrict it in cross-origin content by default, and allow the embedder to selectively allow it per-frame or per-origin as needed.

For workers, the situation should be the same -- but since they're always same-origin, what you should be able to do is *disable* the API in the worker as needed. I haven't completely specced the way that policies should apply to workers, but dedicated workers should be analogous to framed content.

**Comment by annevk** [comment]
A better solution here would be sandboxing the worker I think, so it gets a different origin. You can do that today with a data: URL worker, and hopefully in the future with some kind of HTTP header.

**Comment by inexorabletash** [comment]
Sandboxing should be done at a higher level than just this API, as noted above. Closing out.
