### ISSUE TITLE
Non-normative note about what an upgrade transaction is normally used for

### ISSUE THREAD

**Issue by cynthia** [w3c/IndexedDB#154]
Following up from w3ctag/spec-reviews#153 - reading the spec without enough background got me confused about the purpose of an upgrade transaction.

I think it would be useful to have a non-normative note of what upgrade transaction would normally be used for. (Basically, write down what was discussed in the TAG call earlier today) Somewhere around here? https://w3c.github.io/IndexedDB/#upgrade-transaction

This would be mostly a informative note for content or library (e.g. ORM framework) developers.

**Comment by inexorabletash** [comment]
Good point - I'll rejigger that section.
