### ISSUE TITLE
Add caniuse panels

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#159]
Once https://github.com/Fyrd/caniuse/issues/3193 is addressed we can tag methods with 
```html
<dfn caniuse="IndexedDB" method for=IDBObjectStore>get(|query|)</dfn> 
```
or
```html
<dfn caniuse="IndexedDB2" method for=IDBObjectStore>getAll(|query|, |count|)</dfn>
```
as appropriate to get helpful boxes showing browser support.

**Comment by inexorabletash** [comment]
Merged upstream! Just need to wait for a deploy, I guess.

**Comment by inexorabletash** [comment]
Dropping milestone; per https://github.com/Fyrd/caniuse/issues/3193 the data is merged but not shown on the site, could be a while before it shows up.

(Although I haven't checked to see if bikeshed actually needs it "shown", hrm...)

**Comment by nolanlawson** [comment]
Seems up now: http://caniuse.com/#feat=indexeddb2

**Comment by inexorabletash** [comment]
**TPAC 2019 Web Apps Indexed DB triage notes:**

Dropping this in favor of https://github.com/tabatkins/bikeshed/issues/1524 - no work will be needed here.
