### ISSUE TITLE
Move main branch from gh-pages to master

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#166]
This requires someone with admin permissions on the repo - @siusin maybe you can do it?

1. Main page - Branch dropdown, create `master` branch
2. Settings page - GitHub Pages > Source, select `master` branch.
3. Branches page - Delete `gh-pages` branch

**Comment by siusin** [comment]
1 & 2 done.

@inexorabletash could you double check that the setting of the `master` branch looks good now? If yes, I'll delete the `gh-pages` branch :)

**Comment by inexorabletash** [comment]
@siusin It looks correct so far as I can tell. Thanks!

**Comment by siusin** [comment]
Thanks! Should be all set now.
