### ISSUE TITLE
Update for structured cloning changes in HTML

### ISSUE THREAD

**Issue by domenic** [w3c/IndexedDB#170]
In https://github.com/whatwg/html/commit/97d644c97335956610a31e8ad98d1a388c063e84 HTML changed the setup around structured cloning significantly, in a way that will hopefully benefit IDB a lot. You can now use the StructuredSerialize and StructuredDeserialize operations directly.

Let me know if I can help with this.

**Comment by inexorabletash** [comment]
Thanks. PRs would be welcome, of course, but I'll wrangle it. :) 

The fun bit is where we currently do a clone then (1) look up properties against the clone to avoid side effects - primary key at https://w3c.github.io/IndexedDB/#dom-idbobjectstore-put and index keys at https://w3c.github.io/IndexedDB/#store-a-record-into-an-object-store which looks at the index keys, and (2) inject auto-generated keys in https://w3c.github.io/IndexedDB/#store-a-record-into-an-object-store 

I'll have to see if this can be expressed in terms of serialized records or if we will end up doing a deserialization and reserialization.


. That needs to be a serialize to _record_, deserialize _record_ to _clone_, then discard _clone_ and store _record_ on disk.

**Comment by annevk** [comment]
The other thing Indexed DB should probably define is some kind of Store operation, to define how these records end up on disk (and what further changes need to be made for that).

**Comment by inexorabletash** [comment]
> define how these records end up on disk

Are you thinking of hooks for Storage (which makes sense - e.g. checking for sufficient quota / updating usage), or something specific to serializing the records (which seems like an implementation detail to me)?

**Comment by annevk** [comment]
In particular I think it's not quite an implementation-detail for File, Blob, and SharedArrayBuffer objects. E.g., does File continue to be a pointer or do we make a copy and the same question applies to SharedArrayBuffer. I think the likely answers are different for both.

But it would indeed also be good to integrate with Storage (which also makes it clearer what happens if you clear a box, that Indexed DB disappears too).

**Comment by inexorabletash** [comment]
Of course, this had to materialize the day we were planning to [advance Indexed DB 2.0 to CR](https://github.com/w3c/IndexedDB/issues/165). *sigh*

**Comment by inexorabletash** [comment]
https://github.com/w3c/IndexedDB/pull/171 for the minimum/initial set of changes, without digging into the work @annevk mentions

**Comment by inexorabletash** [comment]
Note that SharedArrayBuffer is taken care of c/o https://github.com/w3c/IndexedDB/issues/152 / https://github.com/w3c/IndexedDB/issues/197

File/Blob could use more definition still.

**Comment by inexorabletash** [comment]
Since this is mostly done, forked https://github.com/w3c/IndexedDB/issues/203 for the specifics of a storage operation distinct beyond StructuredSerializeForStorage.
