### ISSUE TITLE
Given and family are better than first and last

### ISSUE THREAD

**Issue by r12a** [w3c/IndexedDB#172]
2.6. Index
https://www.w3.org/TR/IndexedDB-2/#index-construct

> For example, if an index’s referenced object store contains a record with the key 123 and the value { first: "Alice", last: "Smith" }, and the index’s key path is "first" then the index would contain a record with the key "Alice" and the value 123. 

This is not massively important as comments go, but example 3 is promoting what we'd call bad practise for referring to names, since in Hungary and many other places family names come first and given names come last.  I suggest a simple replacement: first->given, last->family.  

That's still not bulletproof, as you'll see from https://www.w3.org/International/questions/qa-personal-names, but it's better.

**Comment by inexorabletash** [comment]
Thanks - I'll just change `first` to `name` and change `last` to `title` or something.
