### ISSUE TITLE
ASCII character code

### ISSUE THREAD

**Issue by aphillips** [w3c/IndexedDB#175]
https://www.w3.org/TR/IndexedDB-2/#key-path-construct

> A DOMString consisting of two or more identifiers separated by periods (ASCII character code 46, U+002E FULL STOP).

The term "ASCII character code 46" is not preferred, using the Unicode reference as follows it is.

This is I18N comment https://github.com/w3c/i18n-activity/issues/366. Please add i18n-comment label.

**Comment by inexorabletash** [comment]
Thanks - just deleted that sentence fragment.
