### ISSUE TITLE
List of records in "ascending order"

### ISSUE THREAD

**Issue by aphillips** [w3c/IndexedDB#176]
https://www.w3.org/TR/IndexedDB-2/#object-store-construct

> The list is sorted according to key in ascending order. 

"Ascending order" for a list of records is undefined. Is it in order by code unit? 

This is I18N comment https://github.com/w3c/i18n-activity/issues/365. Please add i18n-comment label

**Comment by inexorabletash** [comment]
This would be in key order, i.e. http://w3c.github.io/IndexedDB/#greater-than - I'll linkify the term.

**Comment by inexorabletash** [comment]
PR: https://github.com/w3c/IndexedDB/pull/183

@aphillips - can you take a look?

**Comment by aphillips** [comment]
LGTM
