### ISSUE TITLE
Name content issues?

### ISSUE THREAD

**Issue by aphillips** [w3c/IndexedDB#177]
https://www.w3.org/TR/IndexedDB-2/#object-store-construct

> An object store has a name. The name can be any string value, including the empty string. 

Names are just strings of UTF-16 code units (that's what "any string value" means I think). There are no content restrictions on names. For example, a name could be 14 "shift in" control characters. Or it could consist of a non-character such as U+FFFE. Should "string value" be more closely defined?

This is I18N comment https://github.com/w3c/i18n-activity/issues/364. Please add the i18n-comment label

**Comment by inexorabletash** [comment]
Names are anything which can be specified as a DOMString (WebIDL language) a.k.a. ECMAScript string. So "sequences of 16-bit code units". Valid UTF-16 is not required.

I'll tackle this along with https://github.com/w3c/IndexedDB/issues/178

**Comment by inexorabletash** [comment]
PR: https://github.com/w3c/IndexedDB/pull/184

@aphillips - can you review?

**Comment by aphillips** [comment]
I'm never thrilled by UTF-16 code unit sorting. Yes, sorting by code point is a pain in the ass. But it produces better results and it isn't *that* hard to do. However, I'm willing to hold my nose and won't reopen this issue. The described sort order is deterministic and fast and probably won't be seen by end users often.
