### ISSUE TITLE
Where unique key goes

### ISSUE THREAD

**Issue by aphillips** [w3c/IndexedDB#181]
https://www.w3.org/TR/IndexedDB-2/#introduction

In example 1, the field marked "unique" is `title` but should probably be `isbn`

This is I18N WG comment https://github.com/w3c/i18n-activity/issues/360, but it is a non-I18N comment.

**Comment by inexorabletash** [comment]
(Note that this example dates back to the 1.0 version of the spec.)

`isbn` is used as the primary key; it is inherently unique.

Making `title` unique is a bit contrived - titles are not unique in the real world - but is explicitly called out in the introduction to the example ("This index can be used to look up books by title, and enforces a uniqueness constraint")

If you'd like to rework the examples with alternate properties and data, covering the same set of API usage, PRs welcome.

**Comment by inexorabletash** [comment]
I'm going to close this out - it's intentional and documented within the example. 

(Improvements still welcome, though.)

**Comment by r12a** [comment]
@inexorabletash how about stating in the intro that you are artificially constraining title to be unique for the purposes of the example. Just an idea, since i didn't really understand that from "and enforces a uniqueness constraint" either.

**Comment by r12a** [comment]
I just added that tag to even up things between your repo and our tracker repo. Otherwise, we'll keep getting reports of inconsistencies.  I also proposed to the i18n WG that we close our tracker.

**Comment by inexorabletash** [comment]
Can do a more substantial rework of the example now, so re-opening.

**Comment by inexorabletash** [comment]
@r12a - I put up a PR. Can you review? https://github.com/w3c/IndexedDB/pull/318

I went through the first example's prose, and attempted to reword/simplify. I eliminated use of the passive voice and simplified sentence structure as well.

**Comment by r12a** [comment]
I think that does it for me. Thanks.
