### ISSUE TITLE
Upgrade transaction abort text

### ISSUE THREAD

**Issue by brettz9** [w3c/IndexedDB#186]
I believe this statement in reference to aborting an upgrade transaction:

> The steps are run after the normal steps to abort a transaction, which revert changes to the database including the set of associated object stores and indexes, as well as the change to the version.

should instead state (with changes in bold):

> The steps are run after the **first step of aborting** a transaction, which revert changes to the database including the set of associated object stores and indexes, as well as the change to the version.

**Comment by inexorabletash** [comment]
I think that text dates back to when the normative and non-normative text was not distinguished.

I'll change it to "These steps are run by the steps to abort a transaction as needed." or some such. It doesn't need to be precise about where it is invoked, but "after" is definitely wrong.
