### ISSUE TITLE
Differences between the ED and WD header info

### ISSUE THREAD

**Issue by LJWatson** [w3c/IndexedDB#189]
It looks like the header info in the ED is missing some of the links to "latest published version" etc., although they're all present in the WD. The ED also points people to p-webapps to file issues, instead of Github.

**Comment by inexorabletash** [comment]
For reference:

ED: https://w3c.github.io/IndexedDB/

WD: https://www.w3.org/TR/IndexedDB-2/

**Comment by inexorabletash** [comment]
I can fix the latest published version with a `TR: ....` metadata addition in the bikeshed source.

I'm not sure how to turn off the "Feedback" link which seems to be autogenerated based on the 'webapps' group template/mailing list. @tabatkins - any suggestions?

**Comment by inexorabletash** [comment]
Grumble: `Boilerplate: feedback-header no` omits the __Issue Tracking__ header, not the __Feedback__ header.

**Comment by inexorabletash** [comment]
"Latest published version" link added c/o 56b9d2ec4b98e9a28cd25d5b5a1fb333c8c4b22d

**Comment by inexorabletash** [comment]
Also fleshed out the Editor metadata in bb28908da4bf9bf0d146652b311a1a1f961b0afb

**Comment by inexorabletash** [comment]
And the Feedback links are taken care of in 93e57533ece1030d1ed14d90b79758b1765bb56e
