### ISSUE TITLE
Queueing blocked version change events 

### ISSUE THREAD

**Issue by brettz9** [w3c/IndexedDB#190]
In "The steps to open a database", there is the following:

> If any of the connections in openConnections are still not closed, queue a task to fire a version change event named blocked at request with db’s version and version.

In "The steps to delete a database", there is the following:

> If any of the connections in openConnections are still not closed, fire a version change event named blocked at request with db’s version and null.

The first mentions queuing a task whereas the second does not. Does this not need to be added to both?

**Comment by inexorabletash** [comment]
Probably. Good catch!
