### ISSUE TITLE
create/deleteObjectStore: InvalidStateError logic does not match impls/tests

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#192]
Spec has:

> Let transaction be the upgrade transaction associated with database. If one does not exist or it is finished, throw an "InvalidStateError" DOMException.

But in this case, a TransactionInactiveError is thrown instead in Chrome/Firefox and asserted as such in tests:

```js
tx.abort();
db.createObjectStore('s'); // throws TransactionInactiveError
```

Noted by the ever vigilant @brettz9 over in https://github.com/w3c/web-platform-tests/issues/5612 but it's the spec that's wrong here since impls/tests match.

Unfortunately, the "finished" notion for transactions is a bit squishy. Spec-wise we may be able to just drop the "or it is finished" bit from these methods and then tidy up the transaction lifecycle at some point in the future.

**Comment by inexorabletash** [comment]
I think to fix this properly will require:

* A database may have an associated upgrade transaction, initially null
* Set database's associated upgrade transaction in the steps for running an upgrade transaction
* In the steps to commit/abort a transaction, in the queued task just before we fire the event, we clear the database's associated upgrade transaction

This is because right after calling abort() we would consider the transaction "finished" but yet implementations still give TransactionInactiveError. Implementations still consider the database to have an associated upgrade transaction until the commit/abort actually fires. 

The current "... the upgrade transaction associated with database..." text is squishy since a transaction always has an associated database even after it is finished. So that would invert to "... the database's associated upgrade transaction..."

**Comment by brettz9** [comment]
Btw one nit, FWIW, in regard to `TransactionInactiveError` in another context...

In "steps to asynchronously execute a request", the step "If transaction is not active, throw a "TransactionInactiveError" DOMException." can I think be an assertion as a check appears to always be made before running the steps.

**Comment by inexorabletash** [comment]
Wow, yeah... I thought I'd removed that already as it doesn't even make sense to throw from the async steps.

**Comment by inexorabletash** [comment]
Yep, that's correct.
