### ISSUE TITLE
Define storage operation of non-trivial StructuredSerializeForStorage records (e.g. Blob/File)

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#203]
Forked from https://github.com/w3c/IndexedDB/issues/170

HTML's [StructuredSerializeForStorage](https://html.spec.whatwg.org/multipage/infrastructure.html#structuredserializeforstorage) outputs "records" which are mostly plain-old-data but occasionally not, e.g. File and Blob.

@annevk points out over yonder:

> ... I think it's not quite an implementation-detail for File, Blob, ~~and SharedArrayBuffer~~ objects. E.g., does File continue to be a pointer or do we make a copy ...

(Note that we throw for SABs so that's not an issue)

I need to wrap my head around what's not covered by the [monkey patching](https://html.spec.whatwg.org/multipage/infrastructure.html#monkey-patch-for-blob-and-filelist-objects) details. 

(Since we're already a good bit more rigorous than "v1" I'm not considering this a blocker for "v2" for those who prefer versioned specs.)

**Comment by annevk** [comment]
This seems more like an issue for the File API, no?

**Comment by inexorabletash** [comment]
Yeah. I'll close this out.
