### ISSUE TITLE
Time at TPAC?

### ISSUE THREAD

**Issue by LJWatson** [w3c/IndexedDB#208]
Would you like time at [TPAC](https://www.w3.org/2017/11/TPAC/) to update the WG on progress and/or bring issues up for discussion?

Please let me know by Friday 16th June. If yes, please also let me know how much time you think you'll need.

**Comment by inexorabletash** [comment]
Other than overall spec status (which can go into the normal WG update since there's not much to say - 1-2 minutes tops), I'd like to present the status of our [Indexed DB Observers](https://github.com/WICG/indexed-db-observers) incubation. I think 15 minutes should be sufficient.

**Comment by LJWatson** [comment]
Thanks @inexorabletash. I'll add 15 mins to the schedule.
