### ISSUE TITLE
IndexedDB support React Native

### ISSUE THREAD

**Issue by crazybits** [w3c/IndexedDB#212]
we tried to use indexedDB in React Native, it works fine in debug mode with browser, but always failure when disable remote debug, any idea? does indexed DB support React Native?

**Comment by pwnall** [comment]
IndexedDB is a specification. React Native would have to decide whether to implement the specification in its JavaScript environment or not.

A bit of googling showed me https://github.com/pouchdb/pouchdb/issues/3787 which makes me think that React Native does not currently implement IndexedDB. I hope this helps!
