### ISSUE TITLE
IDB Is Crashing Out

### ISSUE THREAD

**Issue by coderdecoder** [w3c/IndexedDB#214]
Apologies for the lack of details however we are hoping to get some assistance in simply how to get those details.

We are using IDB to store a good amount of data coming off web sockets. It works fine almost all the time but every once in a while IDB just seems to crash. It no longer shows up in the Application tab of dev tools.

chrome://indexeddb-internals/

Won't even load... DBs fro other sites are affected which makes me think we have stumbled on a difficult to reproduce IDB bug.

The only way to fix the issue is to close down Chrome entirely, sometimes killing processes that won't shut down itself, and start it back up again. Basically the whole engine dies.

Does this sound familiar to anyone and any advice on how to trace it to provide more information?

Cheers and thanks,

Walter.

**Comment by pwnall** [comment]
This repository is for the IndexedDB specification, which is implemented by all the browsers. "Crashing" doesn't make much sense in this context.

Please file a bug at https://crbug.com/new.

**Comment by coderdecoder** [comment]
Cheers and thanks. Apologies I got here from google. :)

**Comment by inexorabletash** [comment]
No problem - and please do file a bug report with crbug.com!
