### ISSUE TITLE
lastModifiedDate on File is not a thing

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#215]
There's a clause for evaluating keypaths on File objects with the "lastModifiedDate" property. That property is only implemented in some browsers (Chrome, Firefox, maybe Edge?, but not Safari) but is not in the https://w3c.github.io/FileAPI/ standard.

This should be reconciled - either spec it or remove it from IDB.

**Comment by inexorabletash** [comment]
This is also covered in test that should be updated appropriately:

https://github.com/w3c/web-platform-tests/blob/master/IndexedDB/keypath-special-identifiers.htm#L43

**Comment by inexorabletash** [comment]
It looks like Firefox has managed to unship `lastModifiedDate` (or my note was wrong).

**Comment by inexorabletash** [comment]
HTTPArchive searches are pretty much useless here since it's very common property name used by developers (e.g. JIRA records). We'll need to instrument in Chrome to determine usage.

**Comment by mkruisselbrink** [comment]
Are you looking for usage of `File.lastModifiedDate` in general, or about its usage in IndexedDB specifically? The first one is measured in https://www.chromestatus.com/metrics/feature/timeline/popularity/212 (and removal tracked in https://crbug.com/692728)

(and the chrome bug does indeed mention that Firefox was going to remove lastModifiedDate in FF 61)

**Comment by inexorabletash** [comment]
**TPAC 2019 Web Apps Indexed DB triage notes:**

Delete it from the spec, then it's just a Chrome problem. Good luck, Chrome. (Oh wait....)

**Comment by asutherland** [comment]
The Firefox timeline on this is:
- 2016-06-01: [Deprecated File.lastModifiedDate](https://bugzilla.mozilla.org/show_bug.cgi?id=1048291) in Firefox 49
- 2018-05-04: [Removed File.lastModifiedDate](https://bugzilla.mozilla.org/show_bug.cgi?id=1458883) in Firefox 61. [Intent to unship](https://groups.google.com/d/msg/mozilla.dev.platform/l-WY9qvfUNg/D4hDptSWDgAJ).  We were directly accessing the prototype chain until we landed [bug 1492737](https://bugzilla.mozilla.org/show_bug.cgi?id=1492737) on 2018-09-25.
