### ISSUE TITLE
Support Annotated Types in IDBFactory and IDBObjectStore

### ISSUE THREAD

**Issue by Jasmine-fl** [w3c/IndexedDB#216]
As Web IDL's specifications have changed, Extended Attributes which are applicable to types get to apply to types, not any variables.
Argument's example:
  - Before: [EnforceRange] optional unsigned long court
  - After: optional [EnforceRange] unsigned long court

In the "Before" version,  [EnforceRange] cannot apply to "unsigned long" and it conflicts with the Web IDL's specifications.

**Comment by inexorabletash** [comment]
Yeah, just 10 instances where we need to swap `[EnforceRange]` and `optional`

**Comment by inexorabletash** [comment]
Thanks again!
