### ISSUE TITLE
Should it be clarified that `IDBDatabase.close()` is idempotent?

### ISSUE THREAD

**Issue by isiahmeadows** [w3c/IndexedDB#222]
By reading the spec, it's very obviously implicit that it's idempotent, but the [steps to close a database connection](https://w3c.github.io/IndexedDB/#close-a-database-connection) might want to clarify this and make it explicit by adding an extra initial step like "If the close pending flag is set, abort these steps".

**Comment by inexorabletash** [comment]
Seems fine. Marked as V3 unless someone wants to push for making the change in V2.

**Comment by inexorabletash** [comment]
There's a case where the _close a database connection_ steps are not idempotent:

1. `close()` is called on a connection, which invokes _close a database connection_  - _forced flag_ is implicitly false. 
2. The user agent invokes _close a database connection_ with _forced flag_ true.

It's true that calling `close()` itself is idempotent, though.
