### ISSUE TITLE
indexedDb The first time using the index query takes too long

### ISSUE THREAD

**Issue by wuyandefeixue** [w3c/IndexedDB#225]
usage scenarios:
mobile use webview
After the data is saved into indexedDb, the first time you open the page query is extremely slow。
Query code：
![333](https://user-images.githubusercontent.com/17920500/33206255-92fa3426-d144-11e7-9e4e-89a21bae4bd2.png)

The first result：
![1](https://user-images.githubusercontent.com/17920500/33206049-03b57938-d144-11e7-9263-f07e45277dd0.png)

The second result：
![2](https://user-images.githubusercontent.com/17920500/33206130-3e9aef6a-d144-11e7-9b65-47e3277b1bad.png)

How can I optimize the query?
or Where did I write wrong?

**Comment by inexorabletash** [comment]
This repo is for development of the standard. If you're wanting help with your use of the API consider StackOverflow. If you're hitting performance problems in a particular implementation, file issues against the browser.
