### ISSUE TITLE
Web IDL syntax error?

### ISSUE THREAD

**Issue by xfq** [w3c/IndexedDB#226]
When generating the spec with the latest Bikeshed[1], a fatal error is emitted:

```
FATAL ERROR: IDL SYNTAX ERROR LINE: 17 - skipped: "boolean includes(any key)"
 ✘  Did not generate, due to fatal errors
```

Not sure if it's a bug in the IDL fragment, Bikeshed, or widlparser.

-----

[1] Bikeshed commit: [d1c8ac9ac0bb0f0e970e3942633cfb7d2f7e12e6](https://github.com/tabatkins/bikeshed/commit/d1c8ac9ac0bb0f0e970e3942633cfb7d2f7e12e6)

**Comment by xfq** [comment]
@inexorabletash @tabatkins

**Comment by inexorabletash** [comment]
I don't see an obvious issue with the IDL fragment.

**Comment by inexorabletash** [comment]
It's specific to the word "includes" - `includes` is a keyword in WebIDL, so it's probably making the parser sad.

**Comment by tabatkins** [comment]
Yes, exactly. You can write `boolean _includes(any key)` instead - the leading `_` is stripped from the identifier, and functions as an escaping mechanism.

(Once you switch to using a `_` prefix, Bikeshed should handle things for you automatically; `{{includes()}}` should work fine.)

**Comment by inexorabletash** [comment]
Cool. Just found that part of the WebIDL spec update too. :)

**Comment by inexorabletash** [comment]
Pushed 98b28b9890eb92b36eaadbedb31cea2d3bcd64aa for this... @xfq will that auto-build and deploy ?

**Comment by inexorabletash** [comment]
Looks like it worked. Thanks @xfq and @tabatkins !
