### ISSUE TITLE
Trying to access version 1 of the IndexedDB spec at W3C site, but version 2 is shown.

### ISSUE THREAD

**Issue by Hexstream** [w3c/IndexedDB#227]
Currently, https://www.w3.org/TR/IndexedDB/ returns the same document as https://www.w3.org/TR/IndexedDB-2/. Surely that's wrong?

**Comment by inexorabletash** [comment]
No, it is intentional. The latest published version best describes reality.

You can go back through older versions of the spec through links in the header.

**Comment by inexorabletash** [comment]
Hrm, the "First Edition" link in the summary does just link to the TR link, which is unfortunate.

**Comment by Hexstream** [comment]
Well, I seem to understand that version 1 is a bit more violently deprecated than I expected...

**Comment by inexorabletash** [comment]
Spec versions are a marketing gimmick. Since web APIs are rarely versioned, and since browsers deploy features incrementally, old versions of specs are only of historical interest.

**Comment by inexorabletash** [comment]
Links have been fixed in the Editor's Draft - thanks @xfq !

@xfq - is there a process for updating the TR?

**Comment by xfq** [comment]
@inexorabletash I'm preparing the transition to Recommendation of Indexed DB 2.0, and it will include this change, since it's not a normative change from the Proposed Recommendation on which it is based.

**Comment by inexorabletash** [comment]
Perfect, thanks!

(And agreed, that's not what we want.)

**Comment by xfq** [comment]
The "First Edition" link in https://www.w3.org/TR/IndexedDB-2/ now correctly points to the first edition. Closing.
