### ISSUE TITLE
For schema mutations, should InvalidStateError trump TransactionInactiveError?

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#23]
When calling {create,delete}{ObjectStore,Index} operations, FF throws `InvalidStateError` if there is not an active versionchange transaction, so TransactionInactiveError is never thrown by these methods.

Chrome distinguishes these cases.

The spec wording is slightly ambiguous.

TODO: Check IE and Safari.

**Comment by inexorabletash** [comment]
IE11 doesn't appear to implement the inactive semantics; neither schema changes nor normal operations fail if done asynchronously (e.g. in a setTimeout() rather than IDB callback).

**Comment by benturner** [comment]
Looks like this is an oversight on FF's part. I'll fix to throw TransactionInactiveError if it isn't active.

**Comment by benturner** [comment]
Fixed for FF: https://bugzilla.mozilla.org/show_bug.cgi?id=1176165
