### ISSUE TITLE
List new things in 3.0

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/IndexedDB#251]
For readers coming to the spec from 2.0, it be really great if there was a small section in the spec outlining either what's new in 3.0 (over 2.0) - or what the goals of 3.0 are (sorry if this already there - I wasn't able to find it...).

**Comment by brettz9** [comment]
https://w3c.github.io/IndexedDB/#revision-history

**Comment by marcoscaceres** [comment]
Thanks @brettz9! Totally missed that.
