### ISSUE TITLE
Incoming link from HTML broken

### ISSUE THREAD

**Issue by annevk** [w3c/IndexedDB#256]
HTML uses `#cleanup-indexed-database-transactions` but this document has `#transaction-cleanup-indexed-database-transactions`. Did this change or did we do it incorrectly initially?

**Comment by inexorabletash** [comment]
It looks like Bikeshed is generating the ID here from the section and dfn. Might have been a BS change or a doc refactor.

I'll attempt to get the ID to match what HTML is expecting...

**Comment by inexorabletash** [comment]
Pending an autopublish, should be fixed. LMK if it needs further poking.

**Comment by annevk** [comment]
Thanks, works!
