### ISSUE TITLE
Extract common steps of `IDBObjectStore`'s `put()` and`add()`

### ISSUE THREAD

**Issue by ytausky** [w3c/IndexedDB#261]
Currently the 12 steps are almost identical, the only difference being (as far as I can tell) the value of the *no-overwrite* flag passed to [store a record into an object store](https://w3c.github.io/IndexedDB/#store-a-record-into-an-object-store). Extracting them into a separate named procedure would make it easier for users and implementers to understand the difference between the two methods.

**Comment by inexorabletash** [comment]
Thanks, that's a good refactoring suggestion.

**Comment by inexorabletash** [comment]
PR posted in https://github.com/w3c/IndexedDB/pull/269 - reviews welcome!

**Comment by inexorabletash** [comment]
Thanks @ytausky
