### ISSUE TITLE
Mark IDBCursor's request property as [SameObject]

### ISSUE THREAD

**Issue by Yannic** [w3c/IndexedDB#262]
I'm working on implementing {#255, #257} for Chromium and noticed that the property is not annotated with [SameObject] in the IDL https://w3c.github.io/IndexedDB/#cursor-interface.

From the [WPT for this feature]() and the [video about the spec change](), it looks like [SameObject] should be applied. If it is, I'll submit a PR adding this.

@jakearchibald

**Comment by jakearchibald** [comment]
Yes, it should be `[SameObject]`, sorry!
