### ISSUE TITLE
Site-agnostic databases based on `registerProtocolHandler`

### ISSUE THREAD

**Issue by brettz9** [w3c/IndexedDB#264]
I am wondering if, in place of the perhaps intimidating suggestion brought up through #75, an easier bridge forward to site-agnostic databases might be to tie the privilege to `registerProtocolHandler`.

A special format, such as extending (or replacing) the `web+` prefix, e.g., `web+indexeddb+`, might signify a protocol handler which also would grant access to a shared database as well.

So a site might request permissions like this:

```js
navigator.registerProtocolHandler(
    "web+indexeddb+com_example_dbformats_cdcollection",
    "https://cds.example.com/?collection=%s",
    "CD collection browser"
);
```

The variable `%s` need not be present, but it might be used to allow such
as flagging a default store or view of the collection for the site to open, e.g., 
`web+indexeddb+com_example_dbformats_cdcollection:folk-genre`.

The user would then be asked whether they wished to add `cds.example.com` as a handler for `web+indexeddb+com_example_dbformats_cdcollection` links and also be able to create or access a shared `com_example_dbformats_cdcollection` database (potentially informing the user of any other sites which had already registered for this database format).

If the user approves the protocol, the site could then begin using a shared database (and create the database if the site--or another site--has not already created one) by:

```js
const req = indexedDB.open('com_example_dbformats_cdcollection', undefined, {
  shared: true
});
```

(If the protocol access had *not* yet been created, this might throw or be a no-op.)

The existing UI for storing approved protocols could thus be leveraged.

If there is concern that a user might already have approved such a protocol before knowing it can now support shared database creation/access, the protocol name, e.g., `web+indexeddb+` might have reserved characters would not be permissible in the current scheme.

While there are of course different uses for web protocols and shared databases, I think they may be considered similar enough in both handling custom formats to justify the latter leveraging the former.

**Comment by brettz9** [comment]
FWIW, I've made a similar proposal for shared local storage at https://github.com/brettz9/SharedStorage (also mentioned at https://github.com/WICG/kv-storage/issues/26#issuecomment-429594400 ).

**Comment by pwnall** [comment]
It seems to me that you want a database-as-a-service. Have you considered the SW route?

You'd register a domain and deploy code that installs a SW and fulfills HTTP requests by reading/writing to IndexedDB. You can make up your own REST (or non-REST if you prefer) HTTP API for interacting with the database. I think this works on today's modern browsers, and doesn't require any new permissions.

**Comment by brettz9** [comment]
One can implement it in such a way--as I did in my polyfill--but the problem is that I'd like something site-agnostic.

On the file system, for example, no one word processing app owns your word processing data files, while on the web, we've regressed to data silos where our data is tied to a particular site, with the best case being that sites allow export or to third-party federated services. But nothing for fully offline use and which is agnostic to site.

**Comment by inexorabletash** [comment]
**TPAC 2019 Web Apps Indexed DB triage notes:**

This seems to have the same challenges as [native filesystem](https://github.com/WICG/native-file-system) work where making a shared commons has privacy issues requiring much careful thought, but as noted above unlocks some pretty powerful scenarios.

We also think doing this at the [Storage Buckets](https://github.com/whatwg/storage/issues/2) level is perhaps more appropriate, so it could apply to multiple storage APIs (E.g. [Cache API](https://w3c.github.io/ServiceWorker/#cache-objects)).

**Comment by inexorabletash** [comment]
Let's tackle it as part of buckets.
