### ISSUE TITLE
FPWD of v3? 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/IndexedDB#268]
Hey IDB crew, just wondering if we would like to start thinking of publishing a FPWD of V3? 

Has there been implementation commitment for the new goodies by anyone other than Chrome?

**Comment by inexorabletash** [comment]
For the first question: I was hoping we'd get a few more things in before kicking that off. Based on the last TPAC there seemed to be common interest among implementers in allowing turning off autocommit, but we haven't done any spec work related to that yet. No objection to taking a snapshot, but the normative deltas from V2 are pretty tiny still.

**Comment by marcoscaceres** [comment]
Ok, happy to sit on this for a bit - let's review status at next TPAC and figure out then if we'd like to put out a new draft, if not sooner. In the meantime, I'll try to gauge interest within Mozilla about the new features/changes being proposed (👋 @asutherland).

**Comment by inexorabletash** [comment]
**TPAC 2019 Web Apps Indexed DB triage notes:**

We could probably hit the button on this soon. We expect several more features to be added soon, per https://github.com/w3c/IndexedDB/issues/288#issuecomment-533359849

**Comment by inexorabletash** [comment]
Resolved in https://github.com/w3c/IndexedDB/issues/348 - forgot to close this out.
