### ISSUE TITLE
IDBKeyRange.includes or IDBKeyRange._includes?

### ISSUE THREAD

**Issue by mkruisselbrink** [w3c/IndexedDB#270]
The IDL defines a `_includes()` methods, but then there is an algorithm/description for an `includes()` method. Which one is it supposed to be?

**Comment by inexorabletash** [comment]
The method is `includes()` in usage (and hence but since `includes` is a reserved word in IDL the IDL needs to have the underscore prefix:

See: https://heycam.github.io/webidl/#idl-names

Per #226 bikeshed should handle this... seems like there's still a glitch somewhere though.

**Comment by inexorabletash** [comment]
Might as well use this to track linking.

Not sure what's going on yet. https://github.com/heycam/webidl/issues/733 indicates the BS docs are wrong, at least...

**Comment by mkruisselbrink** [comment]
Ah, interesting. Never came across that before. Good to know that that is a thing...

**Comment by inexorabletash** [comment]
Bikeshed issue: https://github.com/tabatkins/bikeshed/issues/1489

In the Indexed DB 2.0 spec a note was slipped below the IDL fragment in which explained this:

https://www.w3.org/TR/IndexedDB-2/#idbkeyrange

That was done during the final review, didn't make it into 3.0. I'll copy it.
