### ISSUE TITLE
getAll() will crash sometimes in Electron

### ISSUE THREAD

**Issue by kasnihuang** [w3c/IndexedDB#276]
I have a table 'ccc' in indexeddb, and the count of the 'ccc' is more than 35k.
I want to get all data from ccc using getAll(). But sometimes it will crash.
**Note: once there is a crash, using getAll() to fetch the ccc data will crash always.**
**Workaround: clear the table 'ccc', then store data into indexeddb again, getAll() works fine.**

Electron: 5.0.2
Mac OS X: 10.13.6
_This bug can not reproduce in chrome, firefox, just in Electron_

I tried two implementations, but both had this issue.
Code 1:

`
var connection = indexedDB.open('Aaa')
connection.onsuccess = (e) => {
    var db = e.target.result;

    var tr = db.transaction(['ccc'], 'readwrite');

    var objectStore = tr.objectStore('ccc')

    var request = objectStore.getAll();

    request.onsuccess = function() {

        const r = request.result;

        console.info(r && r.length);
    }
}
`
Code 2:
Using Dexie.Collection toArray() api.

**Comment by inexorabletash** [comment]
This repo is for the specification. You need to file an issue against the implementation (i.e. Electron).
