### ISSUE TITLE
Specify keyPath sequence caching behavior on IDBObjectStore

### ISSUE THREAD

**Issue by saschanaz** [w3c/IndexedDB#283]
`objectStore.keyPath === objectStore.keyPath` returns `true` on Firefox and `false` on Chrome when `keyPath` is a sequence. We should probably make this consistent on multiple implementations and add a proper WPT test.

Demo: https://saschanaz.github.io/to-do-notifications/ (Open the console and and try adding an item.)

Probably related to https://github.com/w3c/IndexedDB/issues/235 because using FrozenArray will require the Firefox caching behavior.

PS: Both return a mutable array, but Firefox keeps using the same one (and thus keeps any array mutation) while Chrome seemingly creates a new array every time.

**Comment by inexorabletash** [comment]
The spec says:

However, if this attribute returns an object (specifically an Array), it returns the same object instance every time it is inspected. Changing the properties of the object has no effect on the object store.

So it would just be an implementation bug. File pls?

**Comment by saschanaz** [comment]
Thanks! I filed https://bugs.chromium.org/p/chromium/issues/detail?id=977048, closing.

**Comment by inexorabletash** [comment]
Note that we are missing web platform tests for this, so that's a problem. But I'll include those with the Chrome fix.
