### ISSUE TITLE
Update to Web IDL changes to optional dictionary defaulting

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#285]
See: https://github.com/heycam/webidl/issues/758

Web IDL recently changed to require explicitly listing a default value for defaulted dictionaries instead of it just magically happening.

In practice what that means is that APIs like this:
```webidl
Constructor (BaseAudioContext context, optional AnalyserOptions options)
```
need to be written like this instead:
```webidl
Constructor (BaseAudioContext context, optional AnalyserOptions options = {})
```
(with the addition of `= {}` on the dictionary argument). 

For Indexed DB:

* IDBDatabase (`createObjectStore()`)
* IDBObjectStore (`createIndex()`)
* IDBVersionChangeEvent (constructor)

**Comment by marcoscaceres** [comment]
Hmmm... pr_preview seems to have failed?

**Comment by inexorabletash** [comment]
Blocked on bikeshed updates. See master bug.

**Comment by marcoscaceres** [comment]
Ah, makes sense.
