### ISSUE TITLE
Specification status report for TPAC 2019

### ISSUE THREAD

**Issue by LJWatson** [w3c/IndexedDB#290]
Please can you respond to this comment with a brief specifications status report for the WebApps meeting at TPAC. The report should address the following:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?
* What do you want to achieve for your spec in the next two days (of breakout sessions)?

We're tracking these status reports in [WebApps issue #19](https://github.com/w3c/webappswg/issues/19)

Thanks.

**Comment by inexorabletash** [comment]
Worth mentioning here: one possible future for [KV Storage](https://github.com/WICG/kv-storage) is to merge it into the IDB spec; some of us think it is the best solution to the "make IDB more ergonomic" goal expressed for IDB 3

**Comment by inexorabletash** [comment]
Closing out, FPWD tracked in #268
