### ISSUE TITLE
Array proxies as keys?

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#309]
I noticed that this throws in both Chrome and Firefox:

```js
const k = [1,2,3];
const p = new Proxy(k, {});
indexedDB.cmp(k, p);
```
In Chrome, at least, the proxy fails an internal "is this an array?" check. 

In the spec [convert a value to a key](https://w3c.github.io/IndexedDB/#convert-value-to-key) calls ECMAScript's [IsArray](https://tc39.es/ecma262/#sec-isarray) which would seem to return true for array proxies. 

At the very least, we don't have tests. 

Should we update the spec to exclude proxies, e.g. replacing _"if IsArray(input)"_ with _"if input is an Array exotic object"_?

Alternately, should array proxies be supported? What are the consequences of allowing these? Would the value&rarr;key conversion algorithm potentially blow up in more places?

**Comment by asutherland** [comment]
The algorithms where we `clone a value` already forbid proxies thanks to step 23 of StructuredSerializeInternal (https://html.spec.whatwg.org/#structuredserializeinternal) which prevents use of proxies.

It makes sense to me to also forbid proxies where we directly invoke algorithms without first performing the clone step.

(Also, Firefox/Gecko is a hard no on supporting proxies in IndexedDB were that not already the case!)

**Comment by inexorabletash** [comment]
SGTM. I'll put up a spec PR and wpt PR, time permitting, changing the text to the exotic Array object check.
