### ISSUE TITLE
Add a new event `onbeforecommit` on the interface IDBTransaction 

### ISSUE THREAD

**Issue by Jack-Works** [w3c/IndexedDB#314]
By adding a `onbeforecommit` event, developers can suppress the bad transaction that make the db in an inconsistent state to be committed.

e.g.

```ts
transaction.onbeforecommit = (event) => {
   // when the transaction enter the `onbeforecommit` event, it becomes readonly.
   // it should be enough for consistency check
   if (dbIsConsistent(transaction)) { event.commit() }
   else { event.abort() } // db is inconsistent if we commit this transaction
}
```

**Comment by inexorabletash** [comment]
Can you give examples of the problems you are trying to address with this idea?

Where have you seen the lack of this functionality be a problem?

**Comment by inexorabletash** [comment]
Also, would the discussion in #34 which allow for explicit control over transaction lifetime handle this?

**Comment by Jack-Works** [comment]
Here is my usage:

(I'm using the library `idb` to wrap raw indexeddb as Promise version)
```ts
const t = getTransaction('objectStore', 'readwrite')
await doDangerousAction1(t)
await doDangerousAction2(t)
```

I need a way to do a data consistency check before the transaction end. If the check failed, I want to drop the transaction to prevent my db goes into a inconsistent state.

Currently I use this way to do the job:

```ts
async function consistentDBWriteAccess(action: (t: TransactionType) => Promise<void>) {
    const t = (await db()).transaction(['objectStore'], 'readwrite')
    await action(t)
    await assertDBConsistency(t)
}
```

**Comment by Jack-Works** [comment]
It will be nicer to append the check like this:
```ts
function doDangerousAction1(t) {
   // ....
   t.addEventListener('beforecommit', e => assertDBConsistency(e, t))
}
```

Therefore I can enforce a consistency check before the transaction commit then abort the transaction if it goes into a invalid state.

**Comment by Jack-Works** [comment]
It will also be nice to have a `diff` for what does this transaction changed to complete the check

**Comment by SteveBeckerMSFT** [comment]
TPAC 2024: We discussed and believe that [explicit control over transaction lifetime](https://github.com/w3c/IndexedDB/issues/34) should support the scenarios discussed by this issue.  I'm closing this issue, but please re-activate with example scenarios if we're mistaken.

**Comment by SteveBeckerMSFT** [comment]
Actually closing.  See comment above.
