### ISSUE TITLE
Missing durability attribute in the IDBTransaction interface

### ISSUE THREAD

**Issue by triple-underscore** [w3c/IndexedDB#316]
Which should have been added in the recent commit
https://github.com/w3c/IndexedDB/commit/1a519e7f0a12de4acffc641d3254c1c2d34d380a
probably, to be the following form:

```
interface IDBTransaction : EventTarget {...
    readonly attribute IDBTransactionDurability durability;
...}
```

**Comment by triple-underscore** [comment]
Also, the options argument missing in the DOM intro

> `transaction = connection . transaction(scope [, mode = "readonly"])`

**Comment by inexorabletash** [comment]
Ugh, thanks for catching this. Will fix.
