### ISSUE TITLE
Add type databases(name: string): IDBDatabase[] to IDBFactory

### ISSUE THREAD

**Issue by Maxstgt** [w3c/IndexedDB#322]
I was encountering that this functionality wasn't supported by Typescript. So I was creating an issue in their repo (https://github.com/microsoft/TypeScript/issues/37317). But as `hikarinotomadoi` mentioned correctly, its an editor draft: https://w3c.github.io/IndexedDB/#factory-interface
So I would like to know what your opinion is on that?

**Comment by inexorabletash** [comment]
Browsers having shipped an API is a stronger signal that something is a mostly-permanent part of the web platform than spec status.
