### ISSUE TITLE
Initial DB version (when creating db) is 1 in browsers but 0 in spec

### ISSUE THREAD

**Issue by gouravkhator** [w3c/IndexedDB#332]
In the Spec constructs, section 2.1 Database, its written 
"**When a database is first created, its version is 0 (zero).**" 
But in any browser, if we create a db initially, it shows version 1. 

Also, I cannot pass 0 in the version parameter like: 
indexedDB.open('dbname' , 0 )
It shows type error in console :
"**Failed to execute 'open' on 'IDBFactory': The version provided must not be 0.**"

**Comment by inexorabletash** [comment]
https://w3c.github.io/IndexedDB/#opening

> If |version| is undefined, let |version| be 1 if db is null, or db’s |version| otherwise.

The above makes the default argument 1. Later:

> If |db| is null, let |db| be a new database with name |name|, version 0 (zero), and with no object stores. 

That makes the new database have version 0. Then later:

> Run run an upgrade transaction using |connection|, |version| and |request|.

This starts an upgrade from the initial version (0) to the passed version.

If you check the [IDBVersionChangeEvent](https://w3c.github.io/IndexedDB/#idbversionchangeevent) fired as `upgradeneeded` you will see that for a new database `oldVersion` is 0. Creating a new database is an upgrade from an implicit 0 to the initial version (1, or whatever was specified)
