### ISSUE TITLE
Specification status report for TPAC 2020

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#338]
The specification status report should include:

* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?

**Comment by inexorabletash** [comment]
Progress in the last 12 months:

* Normative: added transaction durability option, per discussion at TPAC 2019
* Normative: remove File lastModifiedDate references, per discussion at TPAC 2019
* Normative: specify that read-only transactions can run in parallel but block a later read/write transaction from starting, and the read/write transactions similarly block later read/write and read-only transactions, matching implementations
* Normative: disallow proxies as keys, matching implementations.
* Normative: make transactions inactive during the value clone process, to prevent side effects (e.g. getters) from re-entering algorithms. 
* Editorial: Alignment with Infra and WebIDL syntax, term and convention updates.

Pending changes:
* (has PR) Accessibility Concerns section addition (awaiting review)
* (has PR) Define Indexed DB as a storage endpoint, per Storage, and integrate with "bottles" terms, etc.
* (has PR) Manual commit per TPAC 2019 discussion - we expect to gain implementation experience and developer feedback here soon.
* (has PR) IDBObjectStore / IDBIndex getAllEntries() per TPAC 2019 discussion  - we expect to gain implementation experience and developer feedback here soon.
* (has PR) IDBCursor close() per TPAC 2019 discussion - no implementation plans I'm aware of
* IDBObjectStore putAll() per TPAC 2019 discussion  - we expect to gain implementation experience and developer feedback here soon, and will write a PR.

**Comment by inexorabletash** [comment]
FYI @LJWatson @marcoscaceres

**Comment by marcoscaceres** [comment]
Moved this to the wiki https://github.com/w3c/IndexedDB/wiki/Specification-status-report-for-TPAC-2020
