### ISSUE TITLE
[Cursor] got value flag.

### ISSUE THREAD

**Issue by cheako** [w3c/IndexedDB#339]
I'm writing wasm rust future Stream.  I haven't tested this yet, I don't want to tease out any undefined behavior.  Rust might be greedy and call poll_next when the cursor is not ready to be read...  It would be important to be able to ask if an operation has completed without having to sync with an onsuccess event.

In addition the examples don't cover the case where something falsy is in the dataset, so presumably some other way of detecting EOF  would be great.

A three state "readyState" for _working_, _readable_, and _reached-end_.

**Comment by inexorabletash** [comment]
The cursor's new values aren't "ready" until the `success` event fires (see #340).

> In addition the examples don't cover the case where something falsy is in the dataset, so presumably some other way of detecting EOF would be great.

If the `success` event fires on the request, and the request's `value` is null (rather than the cursor instance), then the end of the range has been hit. If you were holding the cursor, `cursor.request.value === null` would signal EOF, but again that's not valid to test until the `success` event fires.

**Comment by cheako** [comment]
I agree, that's what I get from the docs and other JS examples.  I think I was wondering if there would ever be a higher level abstraction or if my implementation needed to implement this also.

https://gitlab.com/cheako/websuite-rs/-/blob/59bd04af35d8a8e27f63adb9984378db81658529/idb/src/lib.rs#L425

It's hard to say what I was thinking a year ago, though.  Now looking at it, I don't know why I don't just have a setter/getter for an Option<Result<usize, JsValue>> that is effectively an onsuccess counter or holding the onerror.  With another getter/setter counting the number of successes processed.  I think I just thought that `ready_state()` should be the/a single getter I'm looking for.
