### ISSUE TITLE
Latest Published link is bogus

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#347]
Spec header has: 

> Latest published version:
> https://www.w3.org/TR/IndexedDB-3/

Which is wrong because v3 is not TR, and that link doesn't work.

**Comment by inexorabletash** [comment]
@xfq - this happened in 1f51bffd0826b3b637248a2c19db7e2cb379e565

```
 ED: https://w3c.github.io/IndexedDB/
-TR: https://www.w3.org/TR/IndexedDB-2/
-Level: 2
+TR: https://www.w3.org/TR/IndexedDB-3/
+Level: 3
```

... back in 2018. That seems... wrong? Shouldn't the TR have been left alone? Or maybe Bikeshed's interpretation has changed since then?

**Comment by xfq** [comment]
I added this based on the assumption that the IndexedDB 3.0 FPWD was soon to be published on /TR, but it did not happen. I guess we can just remove this line.
