### ISSUE TITLE
CFC to publish FPWD 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/IndexedDB#348]
Given the good state of the spec, it would be good for us to prepare the document for a First Public Working Draft. In order us to do that, as per the [W3C Process](https://www.w3.org/2019/Process-20190301/#first-wd), we:

- [x] [must record the group's decision to request advancement](https://lists.w3.org/Archives/Public/public-webapps/2021JanMar/0008.html).
- [x] [fill out issue](http://github.com/w3c/transitions) 
- [x] must provide public documentation of any Formal Objections.
- [ ] should provide public documentation of changes that are not substantive - provided via github's commit history. 
- [x] should report any changes in dependencies with other groups.
- [x] should provide information about implementations known to the Working Group.
- [ ] initiate wide review.  

We shouldn't need anything for "documentation of changes that are not substantive", as we can point to the commit history. Our dependencies on other groups haven't changed, and the spec itself lists the known implementations.

**Comment by marcoscaceres** [comment]
@inexorabletash, as part of the publication request, I need to provide any info we might have on implementation interest. Do you happen to know if anyone is experimenting already with any V3 features? If no, that's ok.

**Comment by inexorabletash** [comment]
Do you mean implementations? Searching for "new in this edition" in the spec highlights implementations:
* The IDBFactory databases() method is supported in Chrome 71, Edge 79, and Safari 14.
* The IDBDatabase transaction() durability option is supported in Chrome 82 and Edge 82. 
* The IDBCursor request attribute is supported in Chrome 76, Edge 79, and Firefox 77.
* The IDBTransaction durability attribute is supported in Chrome 82 and Edge 82.
* The IDBTransaction commit() method is supported in Chrome 76, Edge 79, and Firefox 74. 

Or sites that are using them? I can try and dig up some via HTTPArchive...

**Comment by marcoscaceres** [comment]
Just browser implementations will do 👍 Thanks you!!

**Comment by marcoscaceres** [comment]
Kicked off transition request https://github.com/w3c/transitions/issues/318 ... will follow up there an close this once it's published.

**Comment by marcoscaceres** [comment]
Hi @inexorabletash, in w3c/transitions#318, we need to clarify something in the Status of This document. Basically:

> The spec should state whether it's meant to replace IDB 2 or something different.
> For example, the status could say" IDB 3.0 is intended to supersede IDB 2.0".

I checked the Revision History, and it's not completely clear. Would you mind adding something to the Status of This Document?

**Comment by inexorabletash** [comment]
Hey @marcoscaceres - can you take a look at https://github.com/w3c/IndexedDB/pull/349 ?

**Comment by marcoscaceres** [comment]
Closing. FPWD at https://www.w3.org/TR/2021/WD-IndexedDB-3-20210311/
