### ISSUE TITLE
Projection Support

### ISSUE THREAD

**Issue by stefanhaustein** [w3c/IndexedDB#366]
We have some tables that contain columns that can be relatively large, but these large columns aren't actually needed in many or our queries. Of course, we could split the tables, but this isn't desirable due to the additional management overhead and deviation from the expected / "natural" schema.

API Proposal
```
request = store.getAllProjection(keyPath, query [, count])
request = index.getAllProjection(keyPath, query [, count])
```
Retrieves partial data as specified by `keyPath` (as specified in section 2.5 of the IndexedDB spec) for the records matching the given key or key range in query (up to count if given).

This should enable significant performance gains at least in the case where keyPath can be satisfied from an index.

To my understanding, there is currently no way to obtain the index "content" by any other means (other than using cursors or fetching the full rows).

**Comment by SteveBeckerMSFT** [comment]
TPAC 2024: We discussed and agreed with @asutherland comment above.  Closing because of implementation challenges that would prevent any performance gains.
