### ISSUE TITLE
Need to specify what happens if you call `continuePrimaryKey()` on a cursor where the source is an object store. Throw?

### ISSUE THREAD

**Issue by Mguiteria** [w3c/IndexedDB#374]
Need to specify what happens if you call `continuePrimaryKey()` on a cursor where the source is an object store. Throw?

I'm updating the experimental impl in Blink to throw `InvalidAccessError` in this case, pending further discussion.

_Originally posted by @inexorabletash in https://github.com/w3c/IndexedDB/issues/14#issuecomment-106622546_

**Comment by inexorabletash** [comment]
Seems to be a spam bot.
