### ISSUE TITLE
Support Storage Partitioning

### ISSUE THREAD

**Issue by arichiv** [w3c/IndexedDB#382]
Right now IndexedDB is partitioned by the frame's origin, but we should partition third-party iframes independently from first-party frames: https://docs.google.com/document/d/1xd6MXcUhfnZqIe5dt2CTyCn6gEZ7nOezAEWS0W9hwbQ/edit?resourcekey=0-Z5Xn1i5GJ4rit6_93QKIvA

Every time 'origin' is referenced in the spec, we should replace it with a placeholder for origin or double key'd origin depending on how the storage is partitioned.

**Comment by inexorabletash** [comment]
https://github.com/w3c/IndexedDB/pull/334 is a start on the integration.

**Comment by arichiv** [comment]
@inexorabletash would you object to something more like https://github.com/w3c/ServiceWorker/pull/1630/ ? I want to make a limited change just to make it clear the storage key (instead of origin) is the way forward.
