### ISSUE TITLE
IndexedDB not functioning in IE mode of Windows 11 PC's Edge

### ISSUE THREAD

**Issue by satoshi2018** [w3c/IndexedDB#405]
``Product/Service Name, Version, Edition:
Windows 11 Version 22H2 (OS Build 22621.382)
Microsoft Edge Version 101.0.1210.53 (Official build) (64-bit)

Product/Service Feature/Category/Keywords:
Edge's IE mode, indexed DB, localforage

The JavaScript code that utilizes the indexedDB API and the indexedDB wrapper library, localforage, which was working in Edge's IE mode in Windows 10, no longer functions in Windows 11's Edge IE mode.

I have attached a sample program for reference. Could you please investigate the cause of this issue?

```
var request = indexedDB.open('myDatabase', 1);

request.onupgradeneeded = function(event) {
  var db = event.target.result;

};

request.onsuccess = function(event) {
  var db = event.target.result;

};

request.onerror = function(event) {
  console.log('db open error:', event.target.error);
};
```

When executing the sample code, the following error occurs.

`db open error: UnknownError`

**Comment by inexorabletash** [comment]
This repo is about the specification. If you have an issue with an implementation, you should contact the vendor (i.e. Microsoft) or a developer support forum (e.g. StackOverflow).
