### ISSUE TITLE
"opening/closing a database"

### ISSUE THREAD

**Issue by evanstade** [w3c/IndexedDB#410]
AFAICT, a database can be created or deleted. A connection can be opened or closed, but a database cannot be opened or closed. It seems the "opening a database" algorithm should be "opening a connection" (even though it can also create a database) and "closing a database" should be "closing a connection".

(Already, "closing a database" is alternately called "closing a database connection", so that's another option.)

**Comment by inexorabletash** [comment]
Yep, legacy of old spec state that didn't have a distinction between connection and database (I think... it's been a long time).
