### ISSUE TITLE
Documentation correction of step numbers

### ISSUE THREAD

**Issue by chrisrob** [w3c/IndexedDB#418]
Section: 7.1. Extract a key from a value
Para: To evaluate a key path on a value
Step 4: For each identifier of identifiers, jump to the appropriate step below:
.... nested For Each ending in "Otherwise [...steps 1 to 5 ...]" is followed by steps numbered 12 and 13, but should be numbered 5 and 6.

**Comment by inexorabletash** [comment]
Thanks! This seems to be an issue with the W3C stylesheet included by Bikeshed. The `<dt>` elements have `display: list-item` which includes them in the numbering.

**Comment by chrisrob** [comment]
This seems to be fixed. Thank you. Now if I can just get my implementation's act together as quickly as that..:-)
