### ISSUE TITLE
Promise-based API

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#42]
e.g. https://github.com/inexorabletash/indexeddb-promises

**Comment by inexorabletash** [comment]
This also handles "unify exceptions with errors" assuming [async/await syntax](https://github.com/tc39/ecmascript-asyncawait) coming in a future edition of ECMAScript.

**Comment by nuxodin** [comment]
+1

**Comment by petamoriken** [comment]
Since `ExtendableEvent#waitUntil` has [already defined](https://w3c.github.io/ServiceWorker/#extendableevent-interface) in Service Worker, please define `IDBTransaction#waitUntil`.

**Comment by inexorabletash** [comment]
**TPAC 2019 Web Apps Indexed DB triage notes:**

More detailed discussion over in #34 for primitives that would allow wrapping with a promise library, and [KV Storage](https://wicg.github.io/kv-storage/). Closing this out.

**Comment by Kuzcoo** [comment]
Hi,
The discussion is closed but it is not explicit (from an external point of view) that the #34 discussion talks about promise based API.
Is there a will to implement such feature ?

I know there is a quite popular library made by @jakearchibald but I think we should as possible rely on native implementations over library dependencies. This library is pretty popular (2000+ stars), so I think there is a need.
The callback way is very convoluted to the kind of web app that needs such technology as IndexedDB.

As a web developer point of view not familiar with the spec, I find the indexedDB is already quite verbose to use to not benefit from the ease of the promises and by extension async/await

There is the following note on this page: 
https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStoreSync

> The synchronous version of the IndexedDB API was originally intended for use only with Web Workers, and was eventually removed from the spec because its need was questionable. **It may however be reintroduced in the future if there is enough demand from web developers.**

I guess and I hope I am at the right place to ask 😄 

Thank you
