### ISSUE TITLE
Support transaction timeouts

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#43]
Two cases;
- abort a transaction if it hasn't been able to start before the timeout (e.g. other transactions are holding the lock)
- abort a transaction if it hasn't attempted to commit before the timeout (i.e. this transaction is too busy)

Chrome does the second automagically in the case of a hung renderer.

Imported from https://www.w3.org/2008/webapps/wiki/IndexedDatabaseFeatures

**Comment by kristofdegrave** [comment]
In the first case I would use a blocked callback like when you want to open a newer version of the database and have existing connections. This way you give the developer control on how he wants to act on this

**Comment by inexorabletash** [comment]
**TPAC 2019 Web Apps Indexed DB triage notes:**

We think this can be done in user-space, either with just timeouts and abort calls, and/or some of the proposals over in #34
