### ISSUE TITLE
Define flush-to-disk guarantees and control

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#50]
Define flushing guarantees and expose control
e.g. make transactions not flush-to-disk by default, but introduce a "readwriteflush" mode or {flush: true} option

Currently, FF does not flush (but wants an option), Chrome always flushes.

**Comment by sicking** [comment]
Yeah. We found this to be a big performance issue. So we'd definitely like to have this. Most likely the right default would be to not flush since many times developers use IndexedDB as an async version of localStorage.

**Comment by inexorabletash** [comment]
I think we're in favor of this too, just a matter of ensuring out backing store is up for this.

**Comment by beidson** [comment]
The spec has long explicitly required both the A and D of ACID, and probably implicitly requires the C and I. The spec should not get into requiring specific implementation details of that ACIDity.

If an implementation can be ACID without flushing, good for them.

If an implementation see's a noticeable performance hit while flushing, they should work on that.

I think this would be complexity inappropriate for a web-facing API, and we will be against making it a requirement.

**Comment by inexorabletash** [comment]
For performance reasons, we (Chrome) are considering making the flush optional. Example:
```js
db.transaction(scope, "readwrite", {preventFlush: true});
```

**Comment by pwnall** [comment]
I like `relaxedDurability: true` a bit more, because it doesn't make any implementation promises. Also, I think the word `flush` was poisoned, because POSIX has `fflush` (write to OS buffer cache) / `fsync` (write to storage medium) while Windows has `FlushFileBuffers` that writes to the storage medium.

To be clear, we (Chrome) would like to provide a mode that skips writing to the storage medium (`fsync`). We're not currently interested in skipping the `fflush`, because the cost of writing to the OS is small compared to typical IPC overhead.

Also, I wouldn't be against Firefox's approach of disabling `fsync` by default and requiring applications to opt in. Handling power failures is very subtle, and I don't think it's too bad to assume that no apps do it correctly today, so I think it'd make sense to ask developers to explicitly opt into stronger durability guarantees.

**Comment by inexorabletash** [comment]
TPAC 2019 Web Apps breakout: **#CaliforniaRelaxed**

* Attendees agreed with durability control on [storage buckets](https://github.com/whatwg/storage/issues/2) as useful
* Attendees agreed that allowing durability control on transactions was also fine, as long as these are not in conflict
* Proposed switching proposal from a boolean to an enum allows for this: "strict", "relaxed", "default" - the latter would inherit from the bucket's default.

IDL sketch:

```webidl
enum IDBTransactionDurability { "default", "strict", "relaxed" };

dictionary IDBTransactionOptions {
    IDBTransactionDurability durability = "default";
};

// in IDBDatabase:
  ...
  [NewObject] IDBTransaction transaction(
       (DOMString or sequence<DOMString>) storeNames,
       optional IDBTransactionMode mode = "readonly",
       optional IDBTransactionOptions options = {});
  ...
```

@asutherland - how does that look? Happy to bikeshed the naming.

Also: Should we add a readonly `durability` property on `IDBTransaction` to allow introspection? Since this property is a hint to the UA it's not as critical as in other cases.

**Comment by asutherland** [comment]
Looks good.  We already have consensus on this, but we want to make sure the spec definition of durability should come from the buckets spec once that exists.  (Not just inheriting of the behavior.)

At triage just now, we've also agreed that exposing the durability property makes sense.

**Comment by inexorabletash** [comment]
Awesome. Any volunteers to write a spec PR here?

(IMHO we can start sketching out a definition of durability here and then migrate it to Storage when Buckets land.)

**Comment by nolanlawson** [comment]
I see that relaxed durability has landed in Chrome 83: https://www.chromestatus.com/feature/5730701489995776

Is there a benchmark that demonstrates the performance difference between relaxed and strict durability? Looking at [the Chromium commit](https://chromium-review.googlesource.com/c/chromium/src/+/1775557), it references a benchmark in [a Chromium bug](https://crbug.com/785305) that appears to be Google-internal.

I tried it myself, and so far I am not able to see a performance difference, but I'm not sure exactly what kind of workload would suss out the difference. However anecdotally, I do see the same kind of performance differences between Chromium and other engines described in [this post](https://dfahlander.medium.com/chromes-indexeddb-from-best-in-class-to-the-slowest-d34ed14624e0).

**Comment by pwnall** [comment]
@nolanlawson Sorry, I just noticed your comment here. I opened up the bug referenced by the commit. I opened up [the bug mentioned above](https://crbug.com/785305). The benchmark in [this comment](https://crbug.com/1025456#c12) may also help.
