### ISSUE TITLE
Support URLs into records

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#57]
https://lists.w3.org/Archives/Public/public-webapps/2013JulSep/0081.html

Imported from https://www.w3.org/2008/webapps/wiki/IndexedDatabaseFeatures

**Comment by inexorabletash** [comment]
Now that we have [Service Workers](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/) and soon - including [Foreign Fetch](https://wiki.whatwg.org/wiki/Foreign_Fetch) - it's unclear we'd want this, rather than allowing an origin to define its own URL namespace backed by IDB queries.

**Comment by sicking** [comment]
I suspect that this would still be quite useful. If for no other reason than that Service Workers won't be installed on the first run.

I also know that one of the asks from the Google font people was to have a URL which would either quickly succeed, or quickly fail. Either would result in rendering using *some* font, which was the most important thing when rendering a page.

Another way to look at this is: Will Service Workers make people stop using the filesystem:// URL scheme in chrome?

**Comment by inexorabletash** [comment]
FWIW, hacky demo using SWs, to show what's involved

https://gist.github.com/inexorabletash/687e7c5914049536f5a3

**Comment by inexorabletash** [comment]
**TPAC 2019 Web Apps Indexed DB triage notes:**

This is probably better served by [service workers](https://w3c.github.io/ServiceWorker/) and [cache API](https://w3c.github.io/ServiceWorker/#cache-objects), possibly with [static routing](https://github.com/w3c/ServiceWorker/issues/1373) to avoid running any user code.
