### ISSUE TITLE
Allow readwrite transactions restricted to a key range

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#59]
This would allow multiple transactions to operate on the same store

Imported from https://www.w3.org/2008/webapps/wiki/IndexedDatabaseFeatures

**Comment by inexorabletash** [comment]
This seems to vastly complicate the model to me, e.g. indexes get higglety-pigglety.

**Comment by sicking** [comment]
I also wonder how much it would help performance. Something like this makes more sense on a server where you have tons of users accessing the same data store. But it seems less critical on a client where you generally only have one user.

I'd love to see data on how often lock-contention actually happens in practice.

Also: "higglety-pigglety" is awesome :)

**Comment by inexorabletash** [comment]
Closing this one off pending further feedback.
