### ISSUE TITLE
Make it clearer that aborted upgrade transaction deletes new stores/indexes

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#63]
It is pretty clear that when an __upgrade transaction__ aborts the newly created stores and indexes go bye-bye. But it's not explicit that they are considered _deleted_ for the purposes of various algorithms, e.g. clauses like _"if store has been deleted, throw an InvalidStateError exception"_

I'm not sure the best place to put this. Possibly in the first paragraph of [Steps for aborting a transaction]( https://w3c.github.io/IndexedDB/#dfn-steps-for-aborting-a-transaction)

**Comment by sicking** [comment]
Sounds fine with me. I'm guessing that all relevant algorithms should fail anyway since the transaction is no longer active, but it's good to clarify exactly how it's failing and with what exception.

So yes, treating it as deleted objectstores/indexes seem fine with me.
