### ISSUE TITLE
Gather developer feedback on new spec additions

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#65]
Stuff that is recently added but is not shipping in any browser yet not already tracked:

* ~~IDBKeyRange `includes()`~~ &mdash; _shipped in Chrome and Firefox_
* ~~Setters for store/index names~~ &mdash; _shipping in Firefox 49_
* Binary keys &mdash; _experimental in Chrome_
* IDBCursor `continuePrimaryKey()` &mdash; _experimental in Chrome_
* IDBObjectStore `getKey()` &mdash; _experimental in Chrome_

These were spec'd based on initial feedback (and because they had minimal impact of the spec overall), but the priority to implement is unclear.

**Comment by inexorabletash** [comment]
It looks like support for all of these has landed in Firefox. @bevis-tseng or @khuey - do you know what versions everything will appear in?

**Comment by bevis-tseng** [comment]
Landed in FF51. \o/
