### ISSUE TITLE
Ways to detect database manual deletions

### ISSUE THREAD

**Issue by falsandtru** [w3c/IndexedDB#73]
Now we cannot detect database deletions by users because indexeddb does not dispatch onversionchange events in that case. So when we fail to create transactions(`DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing`), we cannot know whether databases connections were closed, or databases were deleted. Could you add the way to know that to the spec?

My implementation is here:

https://github.com/falsandtru/localsocket
https://github.com/falsandtru/localsocket/blob/master/src/layer/infrastructure/indexeddb/model/access.ts

**Comment by inexorabletash** [comment]
See https://w3c.github.io/IndexedDB/#database-connection and search for "forced flag". If the connection is closed by the UA (not script) then a `"close"` event is fired at the connection. Note that only Chrome (so far as I know) currently implements this.

To know if a database was deleted, just re-open, at which point the `oldVersion` will be 0.

**Comment by falsandtru** [comment]
I see, thanks for the teaching.
