### ISSUE TITLE
Specify IDBOpenDBRequest processing as a queue?

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#79]
Consider: 

```js
indexedDB.open(name).onsuccess = e => {console.log('open1'); e.target.result.close(); };
indexedDB.open(name).onsuccess = e=>{ console.log('open2'); e.target.result.close(); };
indexedDB.deleteDatabase(n).onsuccess = e => { console.log('delete'); }
```

* Firefox logs: open1, open2, delete.
* Chrome logs: open1, delete, open2

IIRC we discussed this before. Chrome is following the letter of the spec, that in "steps for deleting a database" the "delete pending flag" is set immediately (no waiting) and in "steps for opening a database" the steps wait on the "delete pending flag". Firefox instead processes IDBOpenDBRequests (opens, deletes) on a named database as a FIFO queue.

This is an observable incompatibility, so we should probably standardize the behavior one way or the other.

**Comment by beidson** [comment]
> Chrome is following the letter of the spec, that in "steps for deleting a database" the "delete pending flag" is set immediately (no waiting)

In v1 of the spec the language for deleteDatabase is "The method then queues up an operation to run the steps for deleting a database"
In v2 of the spec the language for deleteDatabase is "Queue a task to run these substeps:...Let result be the result of running the steps for deleting a database"

In both cases the "steps for deleting a database" are queued and run asynchronously. In neither case is the "delete pending flag" set immediately.

So the example code actually does the following:

indexedDB.open - "The method then queues up an operation to run the steps for opening a database."
indexedDB.open - "The method then queues up an operation to run the steps for opening a database."
indexedDB.deleteDatabase - "The method then queues up an operation to run the steps for deleting a database."

There's no mention of setting the "delete pending flag" anytime before the steps for deleting a database are executed.

Trunk WebKit and Firefox treat these as a queue as mentioned above, and I think they're right.

**Comment by inexorabletash** [comment]
Ah, yes. Are the queues in your implementations specific to the database - (origin, name) pair?

**Comment by beidson** [comment]
The queues are specific to the unique database, yes.

**Comment by inexorabletash** [comment]
Cool. I'll work on improving the spec text and get some web-platform-tests together.

**Comment by inexorabletash** [comment]
Note to self: the V2 spec should not use the "queue a task" phrase here since that's specific to event loops. These queues span execution contexts.

**Comment by nox** [comment]
I'm pretty sure it should still say that it should "queue a task" somewhere, otherwise how does the actual opening of the connection interact with the event queue from the caller?

**Comment by inexorabletash** [comment]
Should be resolved by https://github.com/w3c/IndexedDB/commit/d1147cb70a4b39c236b5d0724f535a78a8d17e1c - take a peek?

**Comment by nox** [comment]
AFAICT this is not good enough, because that means an IDBOpenRequest's result can be set before event handlers were even set on it, given now the setting etc occur in parallel.

**Comment by inexorabletash** [comment]
Thanks @nox - take another look? I'd also forgotten to update the `deleteDatabase` steps.
