### ISSUE TITLE
The steps for opening a database are racy

### ISSUE THREAD

**Issue by nox** [w3c/IndexedDB#81]
If two separate event loops in the same origin queue a task for [opening a database](https://w3c.github.io/IndexedDB/#steps-for-opening-a-database) that didn't exist before in step 3 of [`IDBFactory.open`](https://w3c.github.io/IndexedDB/#dom-idbfactory-open) at the same moment, can't step 4 (*If db is null, let db be a new database with name name, version 0 (zero), and with no object stores*) of the former algorithm create two databases with the same name in the same origin? Shouldn't the spec have prose to prevent that race condition?

Cc @bakulf

**Comment by inexorabletash** [comment]
Yes, this is related to #78 and #79 - the queue that open (and delete) requests are made against is _not_ an event loop, but an abstract queue of open/delete requests associated with an (origin, name) tuple.

**Comment by inexorabletash** [comment]
Should be resolved by https://github.com/w3c/IndexedDB/commit/d1147cb70a4b39c236b5d0724f535a78a8d17e1c - take a peek?
