### ISSUE TITLE
Naming for "v2" ?

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#82]
Before we go to FPWD, we should settle on the name:

* Second Edition
* Level 2
* Version 2
* 2.0
* 2016

Opinions?

**Comment by sicking** [comment]
None at all

**Comment by beidson** [comment]
Not 2016.
"Second Edition" reminds me of Windows 98.

Is there a direct precedent for this type of thing in previous Web APIs?

**Comment by nox** [comment]
Is there any chance this could become a Living Standard?

**Comment by beidson** [comment]
> Is there any chance this could become a Living Standard?

I don't think that's appropriate:
1 - For a specific, relatively limited Web API (e.g. IDB) versus an entire group of associated behaviors (e.g. "HTML5")
2 - Specifically for this API - one about persistent data storage - for which both behavior changes and compatibility changes could be tragic.

**Comment by LJWatson** [comment]
@beidson
With <a href="https://www.w3.org/TR/WebIDL-1/">WebIDL</a> it's "Level n". With <a href="https://w3c.github.io/html/">HTML</a> it's "n.n".

I'd suggest using the "n.n" convention. CSS uses "Level n", but with many modules at the same level that makes more sense. With something like IndexBD - which seems more likely to continue on a linear evolution, 2.0 seems easy to me.

**Comment by inexorabletash** [comment]
I went with 2.0. Internally the spec still uses the term "edition" rather than "level" or "version", pending further feedback.

**Comment by beidson** [comment]
Sounds good to me.
