### ISSUE TITLE
CFC: Publish FPWD of IndexedDB 2.0

### ISSUE THREAD

**Issue by LJWatson** [w3c/IndexedDB#84]
This is a Call For Consensus (CFC) to publish a First Public Working Draft (FPWD) of <a href="http://w3c.github.io/IndexedDB/">IndexedDB 2.0</a>. 

We are still exploring different ways of responding to a CFC. Please choose one of the following methods:
1. Reply or +1 on this Github issue.
2. Reply to the <a href="https://lists.w3.org/Archives/Public/public-webapps/2016JulSep/0026.html">CFC email thread</a> on public-webapps@w3.org.

There is no need to use more than one method. The WP chairs will collate the results across all channels. 

Please respond by end of day on Wednesday 10th August. Positive responses are encouraged, but silence will be taken as consent with the proposal.

**Comment by akuckartz** [comment]
:+1+

**Comment by LJWatson** [comment]
The CFC <a href="https://lists.w3.org/Archives/Public/public-webapps/2016JulSep/0045.html">passed without objection</a>.
