### ISSUE TITLE
Error events from open/deleteDatabase requests - cancelable? bubbles?

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#86]
For both [open](https://w3c.github.io/IndexedDB/#dom-idbfactory-open) and [deleteDatabase](https://w3c.github.io/IndexedDB/#dom-idbfactory-deletedatabase) the spec has:

> The event does bubble but is not cancelable.

In both Chrome and Firefox, the event is cancelable - why? Is this implementation bugs or spec bug?

Since there is no propagation path for these events (_An open request's get the parent algorithm returns null._) what does bubbling mean here?

**Comment by nobso** [comment]
Is this because "IDBRequest" interface is generic and all the requests including 'IDBOpenDBRequest' get the same?

**Comment by inexorabletash** [comment]
@nobso -  Nope. It's done on an event-by-event basis.

**Comment by nobso** [comment]
@inexorabletash Thanks for clarifying that.

**Comment by inexorabletash** [comment]
So `cancelable` matters for `window.onerror` integration (see #49) - if you call `e.preventDefault()` on an open/delete failure then `window.onerror` will not be invoked.

Therefore we almost certainly want the events to be `cancelable` (so: update spec to match implementations as part of #49).

**Comment by inexorabletash** [comment]
For reference, all of (IE11, Safari 10, Chrome 55, Firefox 50) report `true true` for:

```js
r = indexedDB.open('db'+Date.now());
r.onupgradeneeded = function(e) { r.transaction.abort(); };
r.onerror = function(e) { console.log(e.cancelable, e.bubbles); };
```

I suspect it's web compatible to change bubbles to false in all implementations to match the spec; odds are no-one is looking at it. Or we can leave it alone in spec as a quirk. Opinions?

**Comment by inexorabletash** [comment]
Similar finding - when [aborting a transaction](https://w3c.github.io/IndexedDB/#abort-transaction): 

> Dispatch an event at request. The event must use the Event interface and have its type set to "error". The event bubbles and is cancelable.

Canceling here does nothing as the transaction is already doomed. This may be for consistency with other error events, though.

**Comment by inexorabletash** [comment]
FYI, spec text changed here. New text is:

In [open()](https://w3c.github.io/IndexedDB/#dom-idbfactory-open):
>  fire an event named error at request with its bubbles attribute initialized to true.

In [deleteDatabase()](https://w3c.github.io/IndexedDB/#dom-idbfactory-deletedatabase):
> fire an event named error at request with its bubbles attribute initialized to true.

In [abort a transaction](https://w3c.github.io/IndexedDB/#abort-a-transaction)
> Fire an event named error at request with its bubbles and cancelable attributes initialized to true.

**Comment by inexorabletash** [comment]
Tests at https://github.com/w3c/web-platform-tests/pull/5108 for open() and aborting. (deleteDatabase() failures are implementation dependent, can't be tested).

Summarizing the current state of things: 

1. I think spec should say that the error events from open/deleteDatabase are cancelable
2. I think spec should say that the error events from open/deleteDatabase do not bubble

I'll make the change to (1) since that matches implementations. (2) is optional cleanup, will probably punt on it.

**Comment by inexorabletash** [comment]
Fixed (cancelable) in https://github.com/w3c/IndexedDB/commit/c37d44d5b9db7a0520bfc208407b11675f72a086 with tests pending.

Bubbling is weird but I'm leaving it alone unless someone else complains.
