### ISSUE TITLE
Specify timing of transaction deactivation more precisely

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#87]
This occurs in two places:

(1) Calling `transaction()`: https://w3c.github.io/IndexedDB/#dom-idbdatabase-transaction

> (8) When control is returned to the event loop, the implementation must unset the active flag.

(2) Firing a `success` event: https://w3c.github.io/IndexedDB/#fire-success-event

> (2) Set the active flag of transaction.
> (3) Dispatch an event at request. ...
> (4) Unset the active flag of transaction.

In both of these cases the intent is that the deactivation occurs at the end of this "turn" of the event loop when control returns from script to the browser, but _after_ any queued microtasks have been executed.

Is the spec text here precise enough, or can it be improved?

**Comment by brettz9** [comment]
I was just going to ask the question, "If the active flag of the transaction is unset after a single success event, then wouldn't it become impossible for more than a single request to be sent in a transaction?", so at least for me it was not precise enough. :-)

**Comment by brettz9** [comment]
Note that I think there is one other case where this can occur and where requests should still be allowed to continue before deactivation: when an error event is fired but the event is canceled.

**Comment by inexorabletash** [comment]
> "If the active flag of the transaction is unset after a single success event, then wouldn't it become impossible for more than a single request to be sent in a transaction?"

That is covered in https://w3c.github.io/IndexedDB/#fire-success-event and https://w3c.github.io/IndexedDB/#fire-error-event - the transaction is active while the event is being dispatched. Therefore another request can be made, and when that request completes the event will fire, once again setting the transaction to active.

> ...where requests should still be allowed to continue before deactivation: when an error event is fired but the event is canceled

What do you mean by "continue" here?  If you mean that further requests should be allowed, then yes - again, that's allowed during dispatch because the transaction is set to active.

**Comment by inexorabletash** [comment]
Also, to clarify, this issue is specifically about the timing of transaction deactivation relative to microtasks and the event loop. If you believe that the spec has flaws in the _overall_ definition of the transaction lifecycle, please file a separate issue.

**Comment by inexorabletash** [comment]
This also leads to subtlety in the _steps for running an upgrade transaction_:

> When transaction is finished, immediately set request’s transaction to null. This must be done in the same task as the task firing the complete or abort event, but after the event has been fired.

"same task" implicitly includes microtasks (?)

**Comment by smaug----** [comment]
Microtasks run at the end of each event listener when those complete or abort events are dispatched.

**Comment by smaug----** [comment]
The spec is IMO quite clear here, though I'm not familiar with the reasons why the spec wants that behavior. khuey wanted to clear transaction after each microtask, but that actually feels a bit odd behavior to me.

@inexorabletash how does blink handle this? Does it set transaction to null only _after_ event dispatch.
There is also similar '(8) When control is returned to the event loop, the implementation must unset the active flag.'

**Comment by smaug----** [comment]
Hmm, if I read chromium's source code right, it uses EndOfScopeTask which is microtask scheduling.

**Comment by bevis-tseng** [comment]
Here is the example results differently in FF & Chrome:
https://jsfiddle.net/ebe265f5/2/
```javascript
  let request = indexedDB.open("Transaction Life Cycle");
  request.onupgradeneeded = function(event) {
    let db = event.target.result;
    db.createObjectStore("store", {autoIncrement: true});
  };
  
  request.onsuccess = function(event) {
	let db = event.target.result;
    let objectStore = db.transaction("store", "readwrite").objectStore("store");
    let request = objectStore.add({id: 1});
    let txn;
    request.addEventListener("success", function(event) {
      console.log("1st listener");
      txn = db.transaction("store", "readwrite");
    });
    request.addEventListener("success", function(event) {
      console.log("2st listener");
      let objectStore = txn.objectStore("store");
      objectStore.add({id: 2}).onsuccess = function(event) {
        console.log("2nd object is added");
      };
    });
  }
```
In http://w3c.github.io/IndexedDB/#dom-idbdatabase-transaction
If "8. When control is returned to the event loop, the implementation must unset the active flag." means the control is return at the end of the task, then 2nd object could should be added.
However, in Chrome, this is not expected.

@inexorabletash Can this be specified more clearly when then active flag shall be unset? and what's the expected behavior in this case?

**Comment by annevk** [comment]
Also, if this requires a change to how tasks work, please make sure to propagate the change to HTML. It would be good to keep that central description of how tasks work accurate.

**Comment by smaug----** [comment]
This may require some new "after microtask" step, since that is what apparently some browsers have.

**Comment by inexorabletash** [comment]
On vacation for a bit but I'll chime in when I'm back. As a microtask-savvy developer @jakearchibald probably has relevant opinions about what is desirable vs. what just falls out of the specs and implementations.

**Comment by beidson** [comment]
FWIW ToT WebKit matches Chrome here (the transaction is inactive in the second event listener)

We didn't do that intentionally.

**Comment by beidson** [comment]
And by "here" I meant "in Boris' example at https://jsfiddle.net/ebe265f5/2/"

**Comment by smaug----** [comment]
Gecko will probably behave the same way too (once microtask handling around Promises is fixed).

**Comment by inexorabletash** [comment]
Thanks for chiming in, everyone!

> Hmm, if I read chromium's source code right, it uses EndOfScopeTask (which is microtask scheduling) for transaction creation for example,
> but then firing success event uses different setup, since it explicitly sets the active flags.

That's the difference between case 1 and case 2 in the original post. 

=== Case 1 ===

EndOfScopeTask handles case 1; this was introduced before microtasks (though more explicitly IDB-specific prior to refactors); it's only used by IDB. That it's bolted on to microtask processing is just how it evolved in our code base. Hence this tracking bug. :)

Here's Blink's behavior in pseudocode that handles case 1 (the `transaction()` call)

```
run_javascript_callback:
  execute_callback;
  execute_microtasks;
  execute_end_of_scope_tasks;
```

... where any call to `transaction()` would register an end_of_scope task to deactivate it. (Note that "task" here is just a C++ callback, not a spec task.)

This explains the behavior seen in the example by @bevis-tseng - each event callback invocation is a separate run of these steps, so the transaction created by `transaction()` in the first listener's callback is deactivated before the second listener's callback runs.

Note that it is web-observable that this happens after microtasks are run, and that any `transaction()` call in the microtask queue would end up adding additional end-of-scope tasks to the same list. I suspect it would be web-compatible to make changes here if we needed to reduce the magic in the platform here.

=== Case 2 ===

In Blink, the logic that handles activating/deactivating transactions on event dispatches is higher up in the stack. In pseuducode:

```
dispatch_idb_event:
  event = create_event;
  targets = [request, transaction, database];
  transaction.active = true;
  dispatch_event(event, targets);
  transaction.active = false;
```

... where the dispatch_event step encapsulates all of the normal event propagation (or not) and listeners.  Implicitly this runs the steps up above for invoking JS callbacks, so microtasks get run within this as well. I believe this is the bit @smaug---- is referring to as aligning soon in Moz?

...

FWIW, I think the spec describes case 2 sufficiently (but feedback welcome). I believe case 1 is still hand-wavy and probably require propagating changes to HTML (per @annevk) once we agree on how to describe the behavior and what's necessary for compat, etc. But I'm far from certain.

Maybe other implementers could chime in with what they're doing here and we can converge on behavior and then come up with a decent way to describe it?

**Comment by smaug----** [comment]
No, I was referring to case 1. In Gecko we do have "metastablestate" which runs after Promise callbacks, and since I'm fixing Promises to use real microtasks, metastablestate will run like execute_end_of_scope_tasks

**Comment by inexorabletash** [comment]
Cool. I suppose we should try Edge and/or ping @aliams

**Comment by bevis-tseng** [comment]
I saw **2nd object is added** printed in the web console of Edge on Windows 10.

**Comment by jakearchibald** [comment]
I agree that case 2 is taken care of in the spec. Microtasks will run as part of dispatching the event, so it's safe to unset the transaction afterwards.

The only hand-wavey case is:

> When control is returned to the event loop

If this were replaced with "Queue a microtask", I think it will behave like Blink/WebKit, and what @smaug---- is suggesting Gecko will do in future.

**Comment by smaug----** [comment]
No, it is not queue a microtask. It is some post-microtask callback thing what blink (and Gecko sort-of-with-Promises now) have.

**Comment by smaug----** [comment]
Btw, I assume case 1 has been discussed somewhere before, given that Blink and Gecko have this setup. (It is just that in Gecko it is currently bound to Promise scheduling, not microtask scheduling).

**Comment by jakearchibald** [comment]
Hmm yeah, if it was "queue a microtask" then this would fail http://jsbin.com/qivemo/edit?js,console.

I'm not against making it "queue a microtask" to avoid inventing a new thing btw.

**Comment by smaug----** [comment]
queue a microtask would be a breaking change, since if pages happen to use created transactions in promise callbacks, especially in chained callbacks, transaction would stop being useable at some point.
I believe this 'after microtask checkpoint' thing was added on purpose, even though it it super weird in case there are several event listeners. But multiple event listeners is a rare thing, I hope.
 (But I don't know where this after-microtask/promise callback thing was being discussed )

**Comment by annevk** [comment]
https://lists.w3.org/Archives/Public/public-webapps/2014AprJun/thread.html#msg811 has a discussion, but that's post-shipping.

**Comment by smaug----** [comment]
Note to myself that in the spec the transaction created for the upgrade behave quite differently to db.transaction(), as https://github.com/w3c/IndexedDB/issues/87#issuecomment-267456232 hinted.

**Comment by inexorabletash** [comment]
Yeah, upgrade transactions are created "inactive" and case 1 doesn't apply; they do the normal active/inactive flipping around callbacks as other transactions which is case 2.

**Comment by jakearchibald** [comment]
@smaug---- 

> queue a microtask would be a breaking change,

Sure, but given the [lack of browser consistency around microtasks](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/), the breakage might be insignificant.

I don't have strong feelings here, but if there was a desire to avoid creating yet another thing in the event loop, it might be possible.

**Comment by smaug----** [comment]
There isn't much inconsistency here, if we consider only Promise handling, I think, since there is currently 
effectively after-Promise-handling. (and in some browsers Promise callbacks run at microtask checkpoint)

And I don't think there is much difference regarding microtasks in browsers.
It is just that your page is using Promises which not in all the browsers use microtasks (yet).

**Comment by inexorabletash** [comment]
For case 1, HTML's existing [global script clean-up jobs list](https://html.spec.whatwg.org/multipage/webappapis.html#global-script-clean-up-jobs-list) looks almost right, although it is invoked _before_ a microtask checkpoint in [clean up after running script](https://html.spec.whatwg.org/multipage/webappapis.html#clean-up-after-running-script). I don't suppose we can switch the order there? 

Otherwise we need basically the same thing. The [transaction() method's step 8](https://w3c.github.io/IndexedDB/#dom-idbdatabase-transaction) would change to: _Add a step to the **global script clean-up jobs list 2 - electric boogaloo** to unset transaction's active flag._  Same assertions hold: unsetting the flag cannot run scripts and is not sensitive to the order.

**Comment by inexorabletash** [comment]
Hrm, perhaps that only runs for "script" evaluations (scripts, modules, attribute-based event handlers, etc). The bit in "spin the event loop" confused me. I guess we need a similar hook invoked from [Processing model](https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model).

**Comment by inexorabletash** [comment]
Change landed in https://github.com/w3c/IndexedDB/commit/5ae70f2c4ee2e60136ee6d9bdc1ed16cac3853ec
