### ISSUE TITLE
Specify interaction between transaction abort and index/object store renames

### ISSUE THREAD

**Issue by pwnall** [w3c/IndexedDB#89]
Step 1 in the [algorithm for aborting a transaction](https://w3c.github.io/IndexedDB/#abort-transaction) states that all the changes are reverted. This does not specify what happens to the name of an object store / index  that is created and renamed in the same aborted transaction.

For this particular case, Firefox 49/50 does not revert any rename after the transaction is aborted. More formally, it passes this [index rename test](https://codereview.chromium.org/2276593002/diff/480001/third_party/WebKit/LayoutTests/storage/indexeddb/rename-index.html#newcode482), and this [object store rename test](https://codereview.chromium.org/2276593002/diff/480001/third_party/WebKit/LayoutTests/storage/indexeddb/rename-object-store.html#newcode541)

FWIW, I think that the shortest Chromium implementation would result in the same behavior as Firefox. I'd rationalize it as follows. Aborting a transaction marks newly created indexes and object stores as deleted, and reverts the metadata of all the other indexes and object stores modified by the transaction to the corresponding metadata at the beginning of the transaction.

**Comment by inexorabletash** [comment]
Any idea what happens to `indexNames` ?

**Comment by pwnall** [comment]
Apparently, it gets reset to an empty array. I'm done trying to rationalize this 😞

**Comment by bevis-tseng** [comment]
No, Firefox did revert the index name and the objectstore name that were changed in an aborted version-changed transaction.
We have internal test cases covering these. [1][2]

[1] http://searchfox.org/mozilla-central/source/dom/indexedDB/test/unit/test_rename_index.js#149-187
[2] http://searchfox.org/mozilla-central/source/dom/indexedDB/test/unit/test_rename_objectStore.js#130-165

**Comment by bevis-tseng** [comment]
Oops! I misunderstood the scenario you are talking about.
you are talking about more specific case of the renamed index/objectstore that also created in the same transaction.

**Comment by pwnall** [comment]
@bevis-tseng yup, was just writing a response outlining that 😄

**Comment by pwnall** [comment]
Also, to be clear, I can imagine why an implementation would exhibit the current behavior. I was just stating that the spec explanation for the behavior becomes a bit more complicated, as some parts of the metadata get reverted, but others don't.
