### ISSUE TITLE
"Join" queries on multiple object stores

### ISSUE THREAD

**Issue by nolanlawson** [w3c/IndexedDB#92]
PouchDB implements two browser adapters, WebSQL and IndexedDB, both of which are heavily optimized. So it provides a nice point of comparison between the two in browsers that support both (e.g. Chrome), at least for the case of implementing a CouchDB-like API.

Currently one of the biggest performance differences between the WebSQL and IDB adapters is the [allDocs() API](https://pouchdb.com/api.html#batch_fetch), which fetches multiple "documents" by combining two objectStores/tables under the hood (see discussion: https://github.com/pouchdb/pouchdb/issues/3921#issuecomment-107954085).

The reason the WebSQL version is optimized so much more than the IDB version is simple: in WebSQL we build one large `SELECT` statement with a `JOIN` and various conditions on the two tables, whereas in IDB we have to use cursors to iterate through two objectStores, using an object value in one store as the foreign key in the other store. Additionally, any filter conditions on the second store have to be applied in-memory.

Related to #45, it would be nice to have a way to fire multiple queries on multiple object stores at the same time, while defining a foreign key to join the two. I don't yet have any ideas for what this API might look like, but it would be very useful.

**Comment by inexorabletash** [comment]
**TPAC 2019 Web Apps Indexed DB triage notes:**

We've synthesized the core of a proposal at #298 - please take a look.
