### ISSUE TITLE
IDBEnvironment IDL is not valid

### ISSUE THREAD

**Issue by bzbarsky** [w3c/IndexedDB#94]
IDBEnvironment is only exposed in Window, but is implemented by WorkerGlobalScope.  That's not valid IDL.

You probably want to `partial interface WindowOrWorkerGlobalScope` anyway....

**Comment by inexorabletash** [comment]
@bzbarsky - can you review this PR?

https://github.com/w3c/IndexedDB/pull/95

**Comment by inexorabletash** [comment]
Merged in.
